### ISSUE TITLE
Dashboard: Containers: Initial login shows disk space remaining: 0.00GB

### ISSUE THREAD

**Issue by lobsterhands** [codercom/bugs#1]
## What Happened
On my initial load into the dashboard, my container showed disk use at 100% with 0.00GB remaining.
Running `df -h` showed otherwise.

![disk_usage](https://user-images.githubusercontent.com/1688881/43108277-8bebacf8-8ea6-11e8-9747-c0a3993a93d1.png)

The container was turned on during account creation. The disk info values updated properly after a page refresh.

**Comment by ammario** [comment]
cc @jayers

**Comment by lobsterhands** [comment]
A fix for this issue has been deployed.
