### ISSUE TITLE
Stuck on successfully connected to server

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#101]
Aug 7, 2018 at 1:11:41 PM
### What happened
A user reported via zendesk that they are at university with an ethernet connection. They are trying to load into a project and get stuck on connected to server

### Steps to reproduce
1. Create new project on prod
2. Open project in IDE

![screen shot 2018-08-07 at 1 11 11 pm](https://media.gh.coder-internal.com/user/106/files/9ab0aee8-9a43-11e8-93fe-c55d4ffec928)

**zendesk**
389

**Comment by kylecarbs** [comment]
Is this still an issue? Better logging has been added if we can reproduce this.
