### ISSUE TITLE
Users not informed if their container goes offline

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#102]
Aug 8, 2018 at 10:42:26 AM
### What happened
A user reported that they had been using the IDE and left it open overnight. When they came back to the IDE they opened the terminal and it wouldn't respond. The expected behavior is that the IDE will inform the user if their container goes offline and shows a button to refresh. This didn't happen

### Suggested fix
Ensure the reload IDE modal is in place on production

**zendesk ticket**
394

**Comment by Multishifties** [comment]
This just made it into our develop network. Should be ready to deploy to prod after QA approval.
