### ISSUE TITLE
Container getting killed prematurely

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#105]
**Describe the bug**
A user reported that they were unable to save files (bubble wouldn't disappear after saving). They also reported conjure errors in the console after a few hours of coding

**To Reproduce**
1. Go to a project
2. Make some changes to a file
3. Press `control +s` or `command+s`

**Expected behavior**
Files will save reliably

**Comment by nol166** [comment]
Container went offline. We are working on a notification for users who run into this situation.

**Comment by kylecarbs** [comment]
Should be fixed. The container online-time will now renew with activity.
