### ISSUE TITLE
IDE: leaving IDE open overnight causes many self-collaborators to join

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#108]
**Describe the bug**
Leaving the IDE open overnight causes the IDE to be spammed with self-collaborators.

**To Reproduce**
1. Open the IDE
2. Close your laptop lid
3. Open it 24 hours later

I couldn't reproduce on a Windows or Linux laptop. Don't have a Macbook to test with.

**Expected behavior**
The IDE should not be spammed with self-collaborators.

**Screenshots**
![screenshot](https://awau.moe/7d5f96.png)

**Desktop (please complete the following information):**
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
macOS 10.13.6 (17G65)

**Additional context**
Reported via Zendesk `Ticket #384`
Also `Zendesk Ticket #514`

**Comment by NGTmeaty** [comment]
I had this same issue a while back, leaving Coder.com open on my computer, then shutting it down seemed to spawn up a ton of self-collaborators. Haven't seen the issue since.

**Comment by jaymeramsay** [comment]
I'm currently trying to reproduce with a Mac. Others have reported this experience as well.

**Comment by maishsk** [comment]
ChromeOS Version 68.0.3440.87 (Official Build) (32-bit)

**Comment by jaymeramsay** [comment]
This is still a valid issue.
