### ISSUE TITLE
Signup: [Object ProgressEvent] below the signup button

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#110]
**Describe the bug**
During signup, `[Object ProgressEvent]` is shown below the sign up button when clicked. The SMS is still sent, but they can't enter the code. Signup worked after a refresh.

**To Reproduce**
1. Go to signup page, fill it out
2. Click signup button
3. Notice `[Object ProgressEvent]` printed below the button

**Expected behavior**
The signup should work straight away without requiring a refresh or seeing `[Object ProgressEvent]`.

**Screenshots**
n/a

**Additional context**
Reported via Zendesk `Ticket #429`.

**Comment by kylecarbs** [comment]
Should be fixed.
