### ISSUE TITLE
Heavily contended hypervisors can result in save-starved containers

### ISSUE THREAD

**Issue by sreya92** [codercom/bugs#111]
It's possible in a heavily contended hypervisor for a container's autosave process to never acquire the semaphore, effectively starving the container. Despite the starvation a container's filesystem should still be uploaded once it gets unloaded from the hypervisor, however if that same container gets OOM killed it can result in permanent data loss. The fix is to apply a weight to the container so that it gets a higher priority after failing to save. Another fix is in progress and should be merged soon to handle containers getting OOM killed.

**Comment by ammario** [comment]
Fixed
