### ISSUE TITLE
No way to insert a tab, only white space

### ISSUE THREAD

**Issue by Grim102** [codercom/bugs#114]
I'm trying to use makefile for a C++ project, but when I run the "make" command it shows the following error:

`makefile:2: *** missing separator.  Stop.`

My makefile has tabs as separators but the make utility is only seeing white space. I have tried the following IDE settings:

`{
    "editor.insertSpaces": false;
    "editor.autoIndent": false;
    "editor.detectIndentation": false;
    "editor.useTabStops": false;
}`

So far nothings seems to allow my tab key to insert a tab, only white space.

**Comment by Grim102** [comment]
Yes, thank you. That is exactly what I was asking for. The "Convert Indentation to Tabs" option resolved the issue for me.

**Comment by coadler** [comment]
Glad I could help. Let us know if you have any more questions or feedback!

**Comment by Grim102** [comment]
The only feedback I have so far is that this product seems pretty great. I'm telling all the devs I know to check it out.
