### ISSUE TITLE
IDE: files created in the explorer don't show until refresh

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#116]
**Describe the bug**
When creating files using the explorer, they don't immediately show up in the explorer until you refresh the browser.

**To Reproduce**
1. Open the IDE
2. Create a file using the explorer
3. Notice that the file does not display in the explorer
4. Refresh
5. Notice that the file is displayed in the explorer

**Expected behavior**
Files should immediately be shown in the explorer once created.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: iOS 11.4.1
 - Browser: Chrome 68.0.3440.83

**Additional context**
Reported via Zendesk `Ticket #443`.

**Comment by kylecarbs** [comment]
Is this only on an iPad?

**Comment by jaymeramsay** [comment]
No, another user just reported the same behavior. He's on a  Windows 10 64 bit. Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

``Zendesk ticket # 453``

**Comment by lobsterhands** [comment]
I saw this on my machine as well (Ubuntu, latest Chrome)

**Comment by kylecarbs** [comment]
Should be fixed.
