### ISSUE TITLE
Landing: navbar flickers when scrolling on FF

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#118]
**Describe the bug**
When scrolling up and down on the landing page, the navbar at the top of the page flickers.

Not sure if this is fixable, could be some rendering issue in the browser.

**To Reproduce**
1. Go to the landing page
2. Scroll up and down while paying attention to the navbar
3. Notice the flickering on the navbar

**Expected behavior**
The navbar shouldn't flicker when scrolling.

**Screenshots**
[Video](https://awau.moe/962369.mp4)

**Desktop (please complete the following information):**
Windows 10 Home build 17134.165
Firefox 61.0.1 (64 bit)

**Additional context**
Reported via Zendesk `Ticket #445`.

**Comment by jaymeramsay** [comment]
I was able to reproduce this.
