### ISSUE TITLE
Full Site: Recaptcha Logo Everywhere

### ISSUE THREAD

**Issue by jaentwistle** [codercom/bugs#12]
Reported Via Zendesk:

"recaptcha symbol location overlaps scrollbar (Firefox 61.0.1)
https://screencast.com/t/NTm3pokR3U"

**Comment by lobsterhands** [comment]
![captcha](https://user-images.githubusercontent.com/1688881/43115429-77c6951c-8ec9-11e8-9660-39c6c389e7a1.png)

**Comment by nol166** [comment]
This issue has been fixed.
