### ISSUE TITLE
IDE: opening the IDE results in a blank screen

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#120]
**Describe the bug**
Opening the IDE using the Open in IDE button results in the window going blank and nothing happening. Nothing seems to be loading in the background.

**To Reproduce**
1. Open the dashboard
2. Click the Open in IDE button on any project
3. Notice how the page goes blank and nothing happens

**Expected behavior**
The IDE launch log should show, and the IDE should open when the Open in IDE button is clicked.

**Screenshots**
![screenshot](https://awau.moe/cf9268.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.3
 - Browser: Safari 11.0.3 (13604.5.6)

**Additional context**
Zendesk `Ticket #455`.

**Comment by pokemonlover1234** [comment]
I have experienced this as well. Seems to occur randomly.

Windows 10
Chrome
68.0.3440.106 64-bit

**Comment by sreya92** [comment]
A temporary work around is clearing your browser cache.
