### ISSUE TITLE
Pressing escape doesn't close the suggestion menu

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#123]
Aug 14, 2018 at 4:39:03 PM
**What Happened**
A user reported via zendesk that our autocomplete menu doesn't close when pressing escape. This is not expected behavior

**Steps to Reproduce**

1. Open a project
2. Declare a variable 
3. Start typing the variable name elsewhere
4. Press `esc`

**Specs**

1. Operating System: MacOS
2. Browser and Version: Chrome 68
3. Issue present in incognito mode: [yes/no] Yes

**Suggested Fix**
Close the auto-complete menu on `esc`

**Comment by deansheather** [comment]
Zendesk `Ticket #490`.
