### ISSUE TITLE
IDE: terminal sometimes doesn't display correctly

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#127]
**Describe the bug**
One user reported having issues with loading the terminal occasionally. The terminal would load, commands would work but the bash prompt wouldn't display correctly. Refer to screenshot.

**To Reproduce**
1. Open the IDE
2. Open a terminal tab
3. Notice how the bash prompt is broken

**Expected behavior**
Terminal prompt shouldn't break.

**Screenshots**
![screenshot](https://awau.moe/fa99f9.png) (terminal tab)

**Desktop:**
macOS Sierra 10.12.6
Firefox 61.0.2 (64-bit)

**Additional context**
Reported via Discord.

**Comment by jaymeramsay** [comment]
```zendesk ticket 1047```
