### ISSUE TITLE
Copying code snippets that contain unicode characters causes corrupted files

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#130]
**Describe the bug**
Users are reporting that when copying and pasting from a website that has unicode characters, our IDE doesn't know how to deal with these characters and causes the file to become corrupt.

**To Reproduce**
1. Go to [golang.org](https://golang.org/) and copy hello world code
2. Go to coder.com and create a project, and go file
3. Paste the code in your go file
4. In terminal type `go run hello.go`

**Expected behavior**
We format the content of the clipboard to handle differences in encoding

**Screenshots**
![image](https://user-images.githubusercontent.com/5651438/44175730-bd90c280-a0ac-11e8-85a9-573eb15ccf9d.png)

**Additional context**
Chrome 68, MacOS

**Zendesk**
495

**Comment by pokemonlover1234** [comment]
Possibly related to #68

**Comment by nol166** [comment]
zendesk `857`

**Comment by jaymeramsay** [comment]
zendesk ticket ```949``` - markdown and pelican.

**Comment by pokemonlover1234** [comment]
Actually this looks like it would be more related to #179
