### ISSUE TITLE
Container: installing python packages via apt doesn't work

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#131]
**Describe the bug**
Cannot install `software-properties-common` in a fresh container due to an error:
```
...
  File "/usr/bin/py3compile", line 270, in main
    return self._execute('import imp; print(imp.get_tag())', version)
    main()
...
Exception: python3.5 -c 'import imp; print(imp.get_tag())' failed with status code 1
```

**To Reproduce**
1. Open the IDE
2. Open the terminal
3. Run `apt update && apt -y upgrade`
4. Run `apt install -y software-properties-common`

**Expected behavior**
`software-properties-common` should install properly.

**Screenshots**
n/a

**Additional context**
Reported via Zendesk `Ticket #499`.

**Comment by nol166** [comment]
Was able to replicate

**Comment by deansheather** [comment]
This is still occurring. Basically affects any Python packages installed with apt.

**Comment by deansheather** [comment]
Important to note: `python3.5` is actually Python 3.7 in the Python mounts provided by Coder.

Reported via Zendesk `Ticket #962`.
