### ISSUE TITLE
Node mount: npm hangs while installing serverless globally

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#132]
**Describe the bug**
NPM hangs while installing serverless globally using the default node mount.

**To Reproduce**
1. Open the IDE
2. Open the terminal
3. Run `npm i -g serverless`
4. Notice that it hangs

**Expected behavior**
Serverless should install properly.

**Screenshots**
n/a

**Additional context**
Reported via Discord.

**Comment by nol166** [comment]
Was able to replicate

**Comment by deansheather** [comment]
Still able to replicate, user in Discord reports that they were able to replicate too.

Workaround: when the install hangs, you can exit it with `Ctrl+C` and then run `sls` to verify that it installed correctly.

**Comment by nol166** [comment]
still and issue :(

**Comment by nol166** [comment]
New but related issue regarding elm installation on containers zendesk `1531`

**Comment by sreya92** [comment]
@nol166 is this still an issue, i can run `npm -g serverless` without issue in my workspace

**Comment by nol166** [comment]
@sreya92 yeah the hanging issue is fixed. It fails for a different reason now - lack of elevated permissions for child processes spawned by the initial npm install script. I will close this one out.
