### ISSUE TITLE
Docs jitters when scroll all the way down when page doesn't need to scroll down far.

### ISSUE THREAD

**Issue by pokemonlover1234** [codercom/bugs#133]
**Describe the bug**
On pages such as https://docs.coder.com/docs/v013, when you scroll all the way down, the docs jitter. On pages such as https://docs.coder.com/docs/why-use-coder, if you scroll all the way down, then scroll more, it goes slowly down then jumps back up, scrolls down by itself, then back up in the same fashion as v013 but slower.

**To Reproduce**
1. Go to Docs
2. Go to https://docs.coder.com/docs/v013 or https://docs.coder.com/docs/why-use-coder
3. Scroll all the way down until it starts to jump back up
4. Notice it scrolls down automatically then jumps back up again and again.

**Expected behavior**
Scrolling doesn't jitter.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [68.0.3440.106 (Official Build) (64-bit)]

**Comment by jaymeramsay** [comment]
I can't reproduce this issue on Windows 10 Chrome or MacOS chrome.

**Comment by rvrvrv** [comment]
Can't reproduce on Linux + Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Can't reproduce on Linux + Firefox 61.0.1 (64-bit)

**Comment by pokemonlover1234** [comment]
I'll get a video up

**Comment by pokemonlover1234** [comment]
https://youtu.be/AD6cTTi8Psw
Shows jitter behavior on an affected page
Shows slow down/up behavior on an affected page
Shows expected behavior on an unaffected page

**Comment by rvrvrv** [comment]
Thanks for the video! We'll investigate further.

**Comment by NGTmeaty** [comment]
Can't reproduce Windows 10 Chrome 68.0.3440.106
