### ISSUE TITLE
Duplications and slowness with autocompletion in the IDE editor

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#134]
**Describe the bug**
User is experiencing slowness and duplicate entries when using autocompletion in the editor. 

**To Reproduce**
These are the steps I took to try and reproduce it:
1. Open the IDE
2. Create an html file
3. enter `<html><head><script></script></head></html>`
4. in the style tags, type `html {background: aqua}`
5. notice duplications
6. notice the speed of autocompletions

**Expected behavior**
quick autocompletion; no duplications

**Additional context**
``zendesk ticket # 508``

**Comment by deansheather** [comment]
Also affects filename autocompletions:
![screenshot](https://awau.moe/d807ed.png)

**Comment by jaymeramsay** [comment]
related issue: https://github.com/codercom/bugs/issues/82

**Comment by jaymeramsay** [comment]
this appears to be fixed now.
