### ISSUE TITLE
Placeholder text doesn't disappear when filling out the signup form

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#138]
**Describe the bug**
A user was signing up and noticed that the placeholder text in the signup form didn't disappear when they tried to type in their username and email.

**To Reproduce**
*on Browserstack
1. Go to 'homepage'
2. Click on 'Sign Up' in the navbar
3. Start typing in the username input field

**Expected behavior**
placeholder text should disappear

**Screenshots**
![screen shot 2018-08-19 at 4 16 35 pm](https://user-images.githubusercontent.com/28520845/44313301-b0851380-a3cb-11e8-8f4e-e88eea53e9e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: MS Edge

**Additional context**
```Zendesk ticket 547```

**Comment by nol166** [comment]
Deprecated page design
