### ISSUE TITLE
Unable to install dotnetcore into container.

### ISSUE THREAD

**Issue by deccer** [codercom/bugs#140]
**Describe the bug**
Unable to install dotnetcore-2.1 into the container provided after signup. Prerequisites seem to fail to install. `packages-microsoft-prod.deb` contains the sources.list entries and keys for the dotnetcore repos and by calling `dpkg -i packages-microsoft-prod.deb` these should be installed properly.

**To Reproduce**
1. Go to your IDE,
2. Click Terminal
2. type in `cat etc/lsb-release` to determine container os version, it should say Ubuntu 16.04
3. Go to https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current
4. Follow instructions there:
4.1. `wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb`
4.2. `sudo dpkg -i packages-microsoft-prod.deb`
4.3. `sudo apt-get update` 

**Expected behavior**
When running `apt-get update` the following two entries should be part of the output:
`Get:6 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease [2,846 B]`
`Get:7 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages [49.1 kB]`

**Desktop (please complete the following information):**
 - OS: Win10 Professional, [Version 10.0.17134.228]
 - Browser: Opera
 - Version: 54.0.2952.64

**Additional context**
I will attach the copy of the console from inside the container and a copy of my own server.

coder container:
```bash
root@coder:~# wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
root@coder:~# dpkg -i packages-microsoft-prod.deb
(Reading database ... 25311 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.04.1) over (1.0-ubuntu18.04.1) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.04.1) ...
root@coder:~# apt-get update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Fetched 216 kB in 0s (242 kB/s)
Reading package lists... Done
root@coder:~# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@coder:~#
```
`sudo` or not `sudo dpkg` doesnt make a difference

my own server (ubuntu 16.04 lts)
```bash
toth$ wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
toth$ sudo dpkg -i packages-microsoft-prod.deb
Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 126682 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-3) ...
Setting up packages-microsoft-prod (1.0-3) ...
```
note the version `packages-microsoft-prod 1.0-3` ... its `1.0-ubuntu18.04.1` in your container
...and the update on my server reveals the 2 sources from microsoft...
```bash
toth$ sudo apt-get update
Hit:1 http://de.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:5 http://dl.bintray.com/apache/cassandra 310x InRelease
Get:6 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease [2,846 B]
Get:7 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages [49.1 kB]
Fetched 52.0 kB in 0s (82.1 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
```
after that I can install dotnetcore as expected on my own server.

As if the container somehow camouflages as 18.04 and not as 16.04 as expected. `pokemonlover - Resident Kitkat` reported it to be working on his container tho.

**Comment by pokemonlover1234** [comment]
As reported in the issue, i was unable to reproduce. The only major difference was the version installed. Not sure why his attempts to install the 18.04 one.

**Comment by jaymeramsay** [comment]
I am unable to reproduce this issue as well. It looks like the version installed is what's causing it.

**Comment by deccer** [comment]
What do you mean with `looks like the version installed is what's causing it.`?

**Comment by deccer** [comment]
Looks like I was able to fix it. I did reset the container once again, via the container dashboard.
Made sure the Ubuntu version is 16.04, headed to the installation descriptions for dotnetcore.

which are the following according to https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current: 

`wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb`
`dpkg -i packages-microsoft-prod.deb`

When you run `apt-get update` now you see its only http sources, Microsoft's deb is installing https sources so `apt-get` will fail to run for those, since the package `apt-transport-https` is not installed yet. (you can see the error message containing this:)

```
root@coder:~# dpkg -i packages-microsoft-prod.deb
Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 23866 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-3) ...
Setting up packages-microsoft-prod (1.0-3) ...
root@coder:~# apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [87.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [697 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [274 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1082 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [463 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3748 B]
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [873 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.8 kB]
Fetched 3823 kB in 1s (2308 kB/s)
Reading package lists... Done
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/dists/xenial/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Funny that it only happened now and not in the previous description up there.

Anyway, you install the package `apt-transport-https` and just `apt-get update` once more.
If that runs through without problems you can now install dotnetcore-2.1 without any issue.

```
root@coder:~# apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 26.1 kB of archives.
After this operation, 215 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 apt-transport-https amd64 1.2.27 [26.1 kB]
Fetched 26.1 kB in 0s (69.7 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package apt-transport-https.
(Reading database ... 23871 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.2.27_amd64.deb ...
Unpacking apt-transport-https (1.2.27) ...
Setting up apt-transport-https (1.2.27) ...
root@coder:~# apt-get update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Get:4 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease [2846 B]
Hit:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:6 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 Packages [54.9 kB]
Fetched 57.8 kB in 0s (77.7 kB/s)
Reading package lists... Done
root@coder:~#
```

Maybe its a good idea to drop http sources already in your default container and have apt-transport-https installed by default.

Anyway anyway, thanks for looking into it.

**Comment by coadler** [comment]
@deccer I'll make sure we get `apt-transport-https` into the base image. Thanks so much for your research and detailed comments
