### ISSUE TITLE
IDE: "undefined" tab

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#142]
**Describe the bug**
Sometimes when trying to open a file, a tab called `undefined` will appear with no contents.

**To Reproduce**
1. Open the IDE
2. Open a file
3. Close the tab
4. Re-open the file
5. Notice the `undefined` tab appear
6. Refresh and try again and the problem won't occurr

Seems to only happen sometimes. Not sure of the cause.

**Expected behavior**
The file should open without an `undefined` tab appearing.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 68.0.3440.106 64-bit

**Additional context**
Reported via Discord.

**Comment by HorizonShadow** [comment]
Just a couple of additional details: I usually notice this when react's hot-reloader doesn't respond to a file change. I'll close the file, and the hot-reloader will respond. When I try to open the file again, I almost always get `undefined`.

**Comment by nol166** [comment]
This issue has been resolved.
