### ISSUE TITLE
File names are reversed when numbers are at the start 

### ISSUE THREAD

**Issue by NGTmeaty** [codercom/bugs#145]
**Describe the bug**
When numbers are at the start of the file name, file names are reversed. 

**To Reproduce**
1. Go to Coder.com's online IDE
2. Create a file which has numbers at the start of the file(for example 500.html)
3. Open file

**Expected behavior**
The file name should be identical to the regular file name and not be reversed. 

**Screenshots**
https://totally-not.a-sketchy.site/58945e.png
https://owo.whats-th.is/08418a.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 68.0.3440.106

**Additional context**
Reported on discord by Tukib

**Comment by tukib** [comment]
Filenames seem to be split up into sections, separated by periods, underscores, dashes/hyphens, and spaces. If the first 'section' consists of only numbers, this section gets moved to the end of the filename in the tab selection.

Examples:
123 ext -> ext 123
123 test ext -> test ext 123
123 test-ext -> test-ext 123
123-test ext -> test ext-123
