### ISSUE TITLE
The Split Pane icons/labels don't match

### ISSUE THREAD

**Issue by vigneshr23** [codercom/bugs#147]
**Describe the bug**
The Split Pane icons/labels don't match or is interchanged in the code editor.

**To Reproduce**
1. Hover on the Horizontal split pane icon. - the tooltip text shows "Split Pane: Vertical"
2. Hover on the Vertical split pane icon . - the tooltip text shows "Split Pane: Horizontal"

**Expected behavior**
Hovering on the Horizontal split pane icon  #should give the appropriate text in the tooltip - "Split Pane: Horizontal". Same goes for the Vertical split pane.

![horizontal pane](https://user-images.githubusercontent.com/10495874/44506275-3f8f7580-a6c3-11e8-8371-df6bf83cf003.png)

**Comment by NGTmeaty** [comment]
Can reproduce Windows 10 Chrome 68.0.3440.106

**Comment by jaymeramsay** [comment]
Thank you for bringing this to our attention. I'll pass it along to the team!
