### ISSUE TITLE
Coder logo is misplaced on Firefox

### ISSUE THREAD

**Issue by NGTmeaty** [codercom/bugs#148]
**Describe the bug**
On the new loading screen the Coder logo is misplaced on the background

**To Reproduce**
1. Go to Coder.com
2. Open a project
3. See error

**Expected behavior**
The Coder logo should be aligned properly on the background. 

**Screenshots**
https://owo.whats-th.is/032b4c.png
https://owo.whats-th.is/a5f7f7.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 61.0.2
 - 1080p monitor

**Additional context**
Originally spotted on discord

**Comment by nol166** [comment]
Thanks, @NGTmeaty. Our team is aware of this issue and is currently a high priority ticket. Definitely hurts my eyes though.
