### ISSUE TITLE
File tree issues

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#153]
**Describe the bug**
Have two files krate.js & krate-new.js, I deleted krate.js, renamed krate-new.js to be krate.js and went to the terminal to run the app with node krate.js, however when i went back to the krate.js file, both the old krate.js and krate-new.js files existed?

**To Reproduce**
1. Go coder.com
2. Create `krate.js` and `krate-new.js`
3. Delete `krate.js`
4. Rename `krate-new.js` to `krate.js`
5. Run `node krate.js`

**Expected behavior**
after deleting only one file should exist by that name

**Screenshots**
Requesting

**Desktop (please complete the following information):**
Browser: Google Chrome or Chromium 
Operating System: windows

**Comment by NGTmeaty** [comment]
Can't reproduce?

**Comment by jaymeramsay** [comment]
Zendesk ticket ```1023```
