### ISSUE TITLE
Trying to remove everything causes problems

### ISSUE THREAD

**Issue by ZebTheWizard** [codercom/bugs#154]
**Describe the bug**
Trying to wipe the hard drive with the `rm` command messes up stuff. It logs out the current user then makes it impossible to create, delete, or use projects.

**To Reproduce**
1. Go to ide
2. Click on terminal
3. Type `rm -rf /`
4. Wait for errors to occur.

**Expected behavior**

**Screenshots**
<img width="600" alt="screen shot 2018-08-25 at 8 23 24 pm" src="https://user-images.githubusercontent.com/13527122/44623966-c2235b00-a8a4-11e8-818a-f8a53a2ad7b7.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 68

**Comment by deansheather** [comment]
If you wipe your container using the rm command, it deletes all of the files in the container and breaks the operating system installed on it. You should expect issues to pop up when you wipe your container without using the reset button on the containers list.

**Comment by coadler** [comment]
@ZebTheWizard were you able to fix your issues?

**Comment by ZebTheWizard** [comment]
@coadler Yeah, I just thought that it was odd that it logged you out of your account and broke your other projects.

**Comment by coadler** [comment]
when you ran `rm -rf /` did you expect it to only delete that projects files?

**Comment by ZebTheWizard** [comment]
@coadler yes. I get `rm -rf` is very destructive. Users probably already know that, but what is more concerning is how the website reacts to the command.  When the command is ran, the website deletes the current session. Is the session stored on the so called virtual machine?

**Comment by coadler** [comment]
I don't find this concerning. There's nothing we can do to stop a user if they want to `rm -rf /` since it's their container

You're basically deleting the operating system that your stuff is running off of, so I would expect everything to break

**Comment by ammario** [comment]
The logging out of the account is definitely a bug. Every project breaking is expected, because `rm -rf /` will traverse all mounts.

**Comment by jaymeramsay** [comment]
I currently can't reproduce this issue. When I run `rm -rf /`, I get this message:

`rm: it is dangerous to operate recursively on '/'
rm: use --no-preserve-root to override this failsafe
`

And when I try it with `--no-preserve-root`, the command runs. It doesn't however log me out of my account.
