### ISSUE TITLE
Color for project deletion confirmation is not visible unless highlighted.

### ISSUE THREAD

**Issue by ZebTheWizard** [codercom/bugs#155]
Looks like the text is the wrong color. Should probably be black instead of white.

<img width="488" alt="screen shot 2018-08-25 at 8 18 23 pm" src="https://user-images.githubusercontent.com/13527122/44623950-2eea2580-a8a4-11e8-9377-f74e8ed3eead.png">

**Comment by deansheather** [comment]
Zendesk `Ticket #817`.

**Comment by ammario** [comment]
@lobsterhands would it be easy to check text contrast w/ background in the e2e tests?
