### ISSUE TITLE
Cannot change PHP ini

### ISSUE THREAD

**Issue by ZebTheWizard** [codercom/bugs#158]
**Describe the bug**
Users cannot customize the PHP ini file. The ini file used is not accessible or does not exist.

**To Reproduce**
1. Go to project
2. Click on terminal
3. Type `php --ini`. It should say the current ini path is `/tmp/php/build/lib`
4. Type `cat /tmp/php/build/lib` 
5. No such file or directory.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 68

**Comment by deansheather** [comment]
Try setting the `PHPRC` environment variable to where you want to keep your php.ini file. I don't think we give a default php.ini file.

**Comment by ammario** [comment]
Should we provide a sensible default `php.ini`, or can this be closed?

**Comment by ZebTheWizard** [comment]
I think you should. New programmers are not going to know how set an environment variable or know where to find a php.ini

**Comment by jaymeramsay** [comment]
tracking here as a feature: https://github.com/codercom/features/issues/118
