### ISSUE TITLE
Containers in Coder, do they need emptying after use 

### ISSUE THREAD

**Issue by davidpirouet** [codercom/bugs#159]
I did the test, index.js project in my first container it said it is using 3.22GB I delete the project but the container is still as full how do you take it out of use to empty it, if  it has to be emptied?

**Comment by deansheather** [comment]
You can reset (clear) the container by visiting the Dashboard > Containers tab and clicking reset. In the future, please send support requests using the feedback button on the website or by emailing support@coder.com. :smiley:
