### ISSUE TITLE
cyrillic character issue

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#161]
Aug 27, 2018 at 2:42:48 PM
**What Happened**
When entering Cyrillic characters into a file, the file won't run due to illegal characters even after deleting them.

![screen shot 2018-08-27 at 2 46 17 pm](https://media.gh.coder-internal.com/user/106/files/fe60bb8a-aa07-11e8-992a-28471fabea0e)

**Steps to Reproduce**

1. Create `something.js` file
2. type `console.log("Ѐ0400")` 
3. In terminal run `node "something.js'`
4. Remove the `Ѐ0400` and replace it with `"hi"` and then save
5. In terminal run `node "something.js'`
6. Notice the same error

**Specs**

1. Operating System: MacOS
2. Browser and Version: Chrome 68
3. Issue present in incognito mode: [yes/no] Y

**Suggested Fix**
Refuse cyrillic characters from the clipboard

**Comment by NGTmeaty** [comment]
Can't reproduce the errors you are getting, but it is not displaying the Cyrillic characters and adding a weird 0 after replacing it. https://owo.whats-th.is/17191e.png

**Comment by deansheather** [comment]
Zendesk `Ticket #866`.

**Comment by pokemonlover1234** [comment]
related to #68?
