### ISSUE TITLE
IDE: opening large files causes IDE to hang

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#167]
**Describe the bug**
Opening large files (e.g. a 139kb minified css file) causes the IDE to hang. Because the IDE remembers it's previous state, reloading the IDE will reopen the file and cause the issue to keep happening.

**To Reproduce**
1. Open the IDE
2. Open a large file
3. Notice that the IDE hangs
4. Refresh
5. Notice that the file reopens and the IDE hangs again

**Expected behavior**
The file should refuse to open or long open-file operations should be canceled after a timeout (or open in the background).

**Screenshots**
n/a

**Desktop:**
Chrome OS v68.0.3440.87

**Additional context**
Reported via Zendesk `Ticket #714`.

**Comment by pokemonlover1234** [comment]
I've had this issue.

**Comment by nol166** [comment]
Seems to happen with large JSON files as well.

**Comment by pokemonlover1234** [comment]
Happened to me with large js files. Seems to not matter what the file type is
