### ISSUE TITLE
Editor does not seem to get details of file before save

### ISSUE THREAD

**Issue by NGTmeaty** [codercom/bugs#169]
**Describe the bug**
When creating a go file, the project at the top does not seem to be recognized by the editor until you save it, this causes a red line squiggly line and error to be thrown incorrectly. 

**To Reproduce**
1. Type or paste [this code](https://raw.githubusercontent.com/go-training/helloworld/master/main.go) into a new Go file
2. See error on package declaration 

**Expected behavior**
It should recognize the package declaration when it's written or pasted. 

**Screenshots**
https://owo.whats-th.is/2582e5.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 68.0.3440.106

**Comment by nol166** [comment]
I was able to replicate this

**Comment by nol166** [comment]
Deprecated IDE
