### ISSUE TITLE
IDE: clicking "Open in IDE" results in black screen

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#171]
**Describe the bug**
Opening the IDE results in a black screen showing with nothing else.

**To Reproduce**
1. Clear your cache
2. Go to the dashboard
3. Open any project in the IDE
4. Notice that the screen becomes just dark

**Expected behavior**
The IDE should load as expected.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
iPad 9.7 (2017)

**Additional context**
Reported via Zendesk `Ticket #806`.

**Comment by ammario** [comment]
Assuming this is fixed by reloading?

**Comment by Kiri23** [comment]
If you’re using an IPad with a OS version of 9.7 update to the latest version and it will resolve the isue. I was having this problem in OS version 11.1 the reason is that web assembly was broke in this version.
