### ISSUE TITLE
IDE: copying and pasting content in JavaScript files causing corrupted files

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#179]
**Describe the bug**
Copying and pasting content in JavaScript (testing using a file originally created in Eclipse)  files causing corrupted files. The file doesn't seem to contain non-ASCII characters in it

**To Reproduce**
1. Open a JavaScript file in the editor
2. Edit the file using combination of typing and cut and paste (no undo)
3. Save the changes
4. Close the editor
5. Open the editor again

**Expected behavior**
No buggy save behavior.

**Screenshots**
n/a

**Desktop:**
Google Chrome 69 on Windows 10.

**Additional context**
Reported via Zendesk `Ticket #842`.

**Comment by k25nick** [comment]
Below are some detailed steps on how to recreate this issue from scratch. For me this is happening consistently:

- create new project
- open in ide
- open terminal
- git clone https://gitlab.com/k25nick/coder-issue.git
- open index.js
- scroll down to put line 35 in middle of screen
- at end of line 35 press enter to create a new line
- type "var item = null;"
- ctrl-s to save
- close index.js editor
- open index.js
- look at lines 35/36

Expected:
	var id = parseInt(req.params.id);
	var item = null;

Actual:
	var item = null;	var id = parseInt(req.params.id);

Editing the file in multiple places and using cut & paste produces much worse corruption, but the above should be enough to reproduce a simple case.

**Comment by lobsterhands** [comment]
@k25nick, which operating system and editor did you use to create `index.js`?

**Comment by k25nick** [comment]
Hi Lyle,

It was created in Eclipse Photon on Windows 10.

Nick

**Comment by pokemonlover1234** [comment]
During mass changing of a certain piece of reused code in a bunch of js files I did some copying and pasting and experienced this corruption. I noticed something interesting when fixing the corruption however.

the corruption that occurs from pasting is reproducible. I don't mean just I was able to get it to corrupt again, I mean pasting the same thing in the same spot in different files that have the same parts of code around the area you paste causes the SAME exact corruption to occur. fixing the corruption in that area then saving changes the corruption, but once again it's the same exact corruption.

Also I've found a way to fix files the refuse to fix after recreating the file in the file explorer ide. Delete the file using `rm file.js` after copying expected contents, `vim file.js`, then ctrl+shift+v to paste contents. esc to go to vim commands. :w and then :q and the file will be fixed.

**Comment by deansheather** [comment]
One user in Discord came up with a method of uncorrupting files:
1. `Ctrl+Z` so everything goes back to how it was before saving
2. Make a minor change (e.g. delete an empty line)
3. Save file

**Comment by deansheather** [comment]
The same user added:
```
With "corrupted" files it seems saving takes a while, it does some "corrections"
automatically (indentations), messes the file in various ways (duplicate lines,
removes things etc.) and then saves it.
```

**Comment by k25nick** [comment]
I'm not sure using ctrl-z will help. When you're editing the file it looks correct in the editor. Even after saving it still looks correct. It's only when you close the editor and re-open it that you can see the corruption at which point it's too late to use ctrl-z.
