### ISSUE TITLE
IDE: Angular CLI NPM Install Error

### ISSUE THREAD

**Issue by jaentwistle** [codercom/bugs#18]
Submitted Via Zendesk
"Angular CLI npm install error: Install will not complete, errors with a permissions problem. From default directory, used "npm install -g @angular/cli", which is the standard install command, angular's "ng" cli command is not available."

**Comment by deansheather** [comment]
Possibly related to codercom/features#42.

**Comment by kylecarbs** [comment]
Fixed.
