### ISSUE TITLE
IDE UI: find and replace is not displayed correctly

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#180]
**Describe the bug**
Find and replace UI looks broken basically. Hard to explain, check the screenshot.

**To Reproduce**
1. Open the IDE
2. Open any file
3. Click `Ctrl+F` to open the find and replace UI
4. Notice that it looks wrong

**Expected behavior**
The find and replace UI should not look broken.

**Screenshots**
![screenshot](https://awau.moe/88dbdd.png)

**Desktop (please complete the following information):**
Chromium 66.0.3359.170 & Mozilla Firefox
Linux

**Additional context**
Reported via Zendesk `Ticket #871`.

**Comment by pokemonlover1234** [comment]
Can repro

**Comment by jaymeramsay** [comment]
It appears that the window isn't clipped anymore for Windows 10, Linux, and MacOS, but there is an issue made to change the UI/UX for the window altogether. If you have any suggestions, please chime in here.
