### ISSUE TITLE
Arrow keys on iPad occasionally don't function

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#181]
Aug 30, 2018 at 2:20:02 PM
**What Happened**
A user reported that the physical arrow keys on their iPad don't always work in the IDE

**Steps to Reproduce**

1. Open IDE in mobile safari on iPad
2. Open a file 
3. Traverse through the text using the arrow keys 

**Specs**

1. Operating System: iOS
2. Browser and Version: Mobile Safari

**zendesk**
`881`

**Comment by NGTmeaty** [comment]
A update from a Discord user saying that the arrow keys don't function at all, rather than partially not working.

**Comment by deansheather** [comment]
User in Zendesk `Ticket #1195` says that the Cmd key also does not work (i.e. Cmd+S).
