### ISSUE TITLE
Copied and pasted contents of large files aren't saved to disk

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#182]
**Describe the bug**
User tried to copy and paste a file that was around 1000 lines long. When they tried to save it, the file wouldn't save. Also, his terminal froze up. Saving small snippets of code works successfully, though.

**To Reproduce**
Steps I took to reproduce:
1. Open IDE from Dashboard
2. Open terminal
3. Open a `test.js` file
4. Create or find a file sample that is 1000+ lines of code.
5. Copy and paste the contents into the `test.js` file
6. Save it with `Ctrl + S`
7. Open terminal
8. Type `cat test.js` and see what pops up
9. I also ran `ls -l test.js` to see the file size and zero bytes were there.

**Expected behavior**
Large files to save to disk.

**Screenshots**

![image](https://user-images.githubusercontent.com/28520845/44873818-e3969500-ac5e-11e8-9c92-d3a6fcbbfd4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 68

**Additional context**
```zendesk ticket 874```

My terminal didn't freeze up and it appeared that my file did save because the dot in the tab went away.  But when I tried to cat in the terminal, there wasn't any content. When I closed the test.js file and reopened it, all of the previous lines of code were gone.

**Comment by deansheather** [comment]
Possibly related to #167.
