### ISSUE TITLE
clide failed to connect, reconnecting...

### ISSUE THREAD

**Issue by fbenavides69** [codercom/bugs#184]
**Describe the bug**
Afther signing in, I am in the dashboard, I click on the project button and then the initialization page comes up and it never finishes. I get the 'clide failed to connect, reconnecting...' message.

**To Reproduce**
1. Login
2. Goto dashboard
3. click on project button
4. See error at the end repeating it self several times 'clide failed to connect, reconnecting...'

**Expected behavior**
I expected to inside the IDE

**Screenshots**
![image](https://user-images.githubusercontent.com/4228155/44928237-e061de80-ad1c-11e8-88ac-993cdb80c0fa.png)

**Desktop (please complete the following information):**
 - OS: OS X 
 - Browser Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
-

**Comment by jaymeramsay** [comment]
It seems Clide is back to normal at the moment. Are you still experiencing this issue @fbenavides69 ?

**Comment by jaymeramsay** [comment]
So you aren't able to open your IDE currently? I'm guessing you've already tried reloading it. Can you open your dev tools, try loading it again and send over the console errors you receive? Also, if you could send over your workspace id, that'd be helpful. It should be listed in your console. Let me know if you need additional guidance.

**Comment by fbenavides69** [comment]
Hi Jayme,

I have not had time to login again until now, and now it´s working :)

I login using my google email account: francisco.benavides@gmail.com

Rgs!
*Francisco Benavides*
Software Developer & Support Specialist
MX Cel. +52 (1) *449 357 7852*

**Comment by ammario** [comment]
Going to keep this open until the underlying cause is understood.

@scsmithr please take a look.
