### ISSUE TITLE
UI: theme resets after signing out and back in

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#185]
**Describe the bug**
When you log in the theme resets back to the default one.

**To Reproduce**
1. Set the theme to a custom theme
2. Log out
3. Log in
4. Notice that the theme reset back to the default one

**Expected behavior**
The theme should not reset.

**Screenshots**
n/a

**Desktop:**
Browser: Google Chrome
Operating System: windows

**Additional context**
Reported via Zendesk `Ticket #911`.

**Comment by omar-amar** [comment]
as additional information, the theme resets after clearing browser history !

**Comment by nol166** [comment]
Deprecated IDE
