### ISSUE TITLE
Container: can't install mysql-server

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#186]
**Describe the bug**
Installation for `mysql-server` using `apt install` hangs when installing `python3-urllib3`.

**To Reproduce**
1. Open the container terminal or IDE terminal
2. `apt update && apt upgrade -y`
3. `apt install -y mysql-server`
4. Notice that it hangs

**Expected behavior**
`mysql-server` should install successfully.

**Screenshots**
n/a

**Additional context**
Reported via Zendesk `Ticket #919`

**Comment by deansheather** [comment]
Possibly related to #131, as it hangs when installing a python package (no `py3compile` errors are observed, however).

**Comment by pokemonlover1234** [comment]
Can reproduce. Occurs with any package requiring python3-urllib3.

**Comment by Jimpex** [comment]
Having same issue when trying to install the mono compiler for c#... guess I can't run c# in coder for now..

**Comment by jaymeramsay** [comment]
What browser and OS are you using?

**Comment by deansheather** [comment]
Zendesk `Ticket #1299`: the installation now hangs at
```
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
```

**Comment by nol166** [comment]
fixed
