### ISSUE TITLE
IDE: reloading IDE with browser split makes resizing the split janky

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#187]
**Describe the bug**
When you reload an IDE that has a browser split, the resize mechanism for the split breaks when moving it.

**To Reproduce**
1. Open the IDE
2. Open the IDE browser
    1. Open a terminal
    2. Run `python3 -m -http.server`
    3. Open the IDE browser from the Connect to Your Web Server menu
3. Split the editor by switching to the terminal tab and drag the browser tab to the right side of the screen
4. Open a file in the left split
5. Resize the browser split from left to right and note the behavior (intended behavior)
6. Reload the browser and wait for the IDE to reconnect
7. Try to resize the browser split from left to right
8. Notice that the browser split doesn't resize as usual

**Expected behavior**
The splits should resize as usual.

**Screenshots**
[Video](https://awau.moe/08904a.mp4)

**Desktop (please complete the following information):**
Browser: Google Chrome or Chromium 
Operating System: Windows or Linux

**Additional context**
Reported via Zendesk `Ticket #925`.

**Comment by nol166** [comment]
Deprecated
