### ISSUE TITLE
IDE: Polish symbols saving incorrectly

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#188]
**Describe the bug**
Polish symbols don't seem to save properly when written to files using the IDE.

**To Reproduce**
1. Open the IDE
2. Create a HTML file: `index.html`
3. Edit the file and add charset UTF-8 tag
4. Add Polish symbols to the file
5. Save the file
6. `cat` the file and notice the output (symbols replaced with underscores)
7. Start a web server: `python3 -m http.server`
8. Open `index.html` in a web browser
9. Notice the broken Polish symbols

**Expected behavior**
Polish symbols should save correctly.

**Screenshots**
File in the IDE: https://i.imgur.com/eCsJh2J.png
`cat` command result (it looks strange for me): https://i.imgur.com/2P1eq9F.png
Browser output: https://i.imgur.com/koXaRZF.png

**Desktop:**
Browser: Google Chrome
Operating System: Windows

**Additional context**
Reported via Zendesk `Ticket #943`.

**Comment by deansheather** [comment]
Possibly related to #161.

**Comment by pokemonlover1234** [comment]
Is it possible that the terminal is unable to display these characters? Or is it supposed to?

**Comment by abugjewski** [comment]
Could it be something related to keyboard shortcuts maybe? Like those making Polish symbols (alt + letter)  have some unexpected (or maybe expected?) behavior in the Coder IDE?
