### ISSUE TITLE
Code sync on internet failure and offline mode

### ISSUE THREAD

**Issue by raunakhajela** [codercom/bugs#189]
**Describe the bug**
When the internet is disconnected then after reconnection editor just freezes and you have to refresh the whole page which sometimes results in the loss of code.

**Expected behavior**
After internet failure, coder.com should work in an offline mode and reconnect where you left off on internet access. Similar to Google apps.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 68.0.3440.106

**Comment by NGTmeaty** [comment]
Not sure how possible this would be, Most things on Coder.com save or run on your container, losing internet connectivity would mean none of the features that rely on your container. But I do see your point with losing code, and as a safety pre-caution, having some kind of message saying that you are disconnected and don't have internet could be nice.

**Comment by raunakhajela** [comment]
Yes, there should be a way. I create a node app and after internet failure and reconnection was unable to type. Had to refresh again and then it worked.
