### ISSUE TITLE
Git tab in IDE

### ISSUE THREAD

**Issue by raunakhajela** [codercom/bugs#190]
To commit changes right now you have to use terminal and fire git commands which is fine. But is it possible to add an extra tab for Git in the IDE itself for committing changes just like we have in VS Code.?

**Comment by xaanit** [comment]
For feature requests you want [this repo](https://github.com/codercom/features/issues). But better git integration is already planned.

**Comment by raunakhajela** [comment]
Done and closing issue on bug requests.
