### ISSUE TITLE
IDE: collaborator names are hidden when they are on the first line

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#191]
**Describe the bug**
When a collaborator is editing in the first line of the file, their name is hidden.

**To Reproduce**
1. Open the IDE
2. Invite a friend to the project
3. Both users open the same file with multiple lines
4. One user moves their cursor to the first line
5. The other user should note that they cannot see the other user's name

**Expected behavior**
The name should still be visible (somehow).

**Screenshots**
n/a

**Desktop:**
Browser: Google Chrome
Operating System: Windows

**Additional context**
Reported via Zendesk `Ticket #977`.

**Comment by nol166** [comment]
fixed
