### ISSUE TITLE
PHP has a broken autocompletion

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#193]
**Describe the bug**
When a user tries to invoke intellisense with `php`, `php<?php` shows up. In fact, any word you type will have `<?php` attached to the end of it. Example: `hello<?php`

**To Reproduce**
1. Open your IDE
2. create a `test.php` file
3. Type `php` and hit `enter` 
4. notice the autocompletion
5. Try typing other words too and hit `enter` afterward

**Expected behavior**
The user expects to see `<?php?>` once they hit `enter`, and at the very least `<?php` shouldn't appear after any words.

**Screenshots**
<img width="472" alt="screen shot 2018-09-06 at 1 25 28 pm" src="https://user-images.githubusercontent.com/28520845/45177374-5d3aff80-b1d8-11e8-8363-2a6828de6b92.png">

**Desktop (please complete the following information):**
 MacOS High Sierra
Safari Version 11.1.2 (13605.3.8)
Incognito Mode: No

**Additional context**
```Zendesk ticket 980```

**Comment by lobsterhands** [comment]
I see differences in `.php` file behavior between Chrome and Firefox (on Linux).
Chrome does not offer autocomplete, and the text is a different color.
Firefox acts the way @jaymeramsay mentioned.

**Chrome**
![screenshot from 2018-09-07 12-30-45](https://user-images.githubusercontent.com/1688881/45233932-e6663b00-b299-11e8-9fbf-c16aca4fc662.png)

**Firefox**
![screenshot from 2018-09-07 12-30-56](https://user-images.githubusercontent.com/1688881/45233933-e6663b00-b299-11e8-8af3-7877f5c31fb2.png)
