### ISSUE TITLE
Visual issues on Landing page mobile view

### ISSUE THREAD

**Issue by jkimmilnes** [codercom/bugs#194]
**Describe the bug**
1. Under "Extreme Speed," there are two arrow icons next to "Watch the Video." The right icon is partially cut off. This one should be removed. 
2. By swiping left and right, you see extra white space on the screen. If you swipe all the way to the right, the white space stays on the right. The mobile screen shouldn't show any white space. 

**Screenshots**
![img_0933](https://user-images.githubusercontent.com/42357521/45180646-962ba200-b1e1-11e8-8215-986975d1248d.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS 11.4.1
 - Browser: Chrome

**Comment by nol166** [comment]
Home page deprecated
