### ISSUE TITLE
Blank screen on Google authentication

### ISSUE THREAD

**Issue by raunakhajela** [codercom/bugs#196]
**Describe the bug**
I log in to coder.com through my google account and it shows a blank screen when you login first time until you refresh the page. I don't think this is a very big bug but it should be fixed for a better user experience. 

**Desktop (please complete the following information):**
 - OS: Windows 7 64 Bit
 - Browser: Chrome
 - Version: 69.0.3497.81

**Comment by nol166** [comment]
@raunakhajela Thank you for reporting this. I will let our team know.

**Comment by nol166** [comment]
fixed
