### ISSUE TITLE
Google signup process isn't successful

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#197]
**Describe the bug**
User is trying to use Google to sign up but once they try to navigate back to Coder from the google page, nothing happens.

**To Reproduce**
Unable to reproduce at this time, but the steps regardless would be:
1. Click sign up from Coder homepage navbar
2. Click on 'Sign up with Google'
3. Go through the signup process
4. Click `create account` submit button
5. Notice if it navigates to Coder or not

**Expected behavior**
Once you fill out the signup form and click the google account you want to use, it should then navigate back to the Coder dashboard.

**Desktop (please complete the following information):**
 MacOs/Safari

**Additional context**
```Zendesk ticket 1022```

**Comment by nol166** [comment]
fixed
