### ISSUE TITLE
Electron doesn't work upon execution

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#202]
**Describe the bug**
After installing electron, the execution fails. It states that you should delete node modules and try again

**To Reproduce**
1. Go to coder.com
2. Open the terminal
3. Type `npm install electron --save-dev`
4. Type `electron .`
5. See error

**Expected behavior**
Electron runs

**Screenshots**
![screen shot 2018-09-14 at 5 41 24 pm](https://user-images.githubusercontent.com/5651438/45578165-6f0a4b80-b845-11e8-8f7a-468a76bb757d.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 68
 - Version 68

**Comment by deansheather** [comment]
Electron fails to install globally, but installs properly when you use `npm install electron --save-dev`. The third reproduction step should actually be `npm install electron --global`.

If you do `npm install electron --save-dev` and then use `node_modules/.bin/electron .` to start Electron, you'll notice that nothing appears as it's a graphical application and [Coder doesn't support X apps](https://github.com/codercom/features/issues/110).
