### ISSUE TITLE
IDE: Typescript and JavaScript doesn't have working autocomplete

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#204]
**Describe the bug**
Autocomplete doesn't show for anything in Typescript or JavaScript.

**To Reproduce**
1. Open the IDE
2. Open a Typescript .ts or JavaScript .js file
3. Edit the file
4. Notice that there is no autocompletions

**Expected behavior**
Autocompletions should work in Typescript and JavaScript files.

**Screenshots**
n/a

**Additional context**
Reported via Discord.

**Comment by jaymeramsay** [comment]
The team is actively working on making necessary changes to the editor. This is on its way to being fixed.
