### ISSUE TITLE
IDE will not load

### ISSUE THREAD

**Issue by npd1987** [codercom/bugs#206]
**Describe the bug**
The IDE will not load
Error message: "[Clide] Failed to connect, reconnecting..."

**To Reproduce**
1. Go to 'Dashboard'
2. Click on "Open in IDE" for a project

**Expected behavior**
The IDE will load

**Screenshots**
![image](https://user-images.githubusercontent.com/43356040/45650612-da9a2600-ba9c-11e8-9ce3-c54660b66e89.png)
Video of error: https://gfycat.com/DeterminedParallelHoopoe

**Desktop (please complete the following information):**
 - OS: Chrome OS - Version 68.0.3440.118 (Official Build) (64-bit)
 - Browser: Chrome
 - 68

**Additional context**
I have tried creating a new project, which got the same error as my existing project.
I have logged out and logged back in again, with the same error occurring still.

**Comment by npd1987** [comment]
Thanks coadler!

**Comment by coadler** [comment]
@npd1987 looks like your project's container is taking an abnormal amount of time to spawn, could you try creating a new project and launching that?

**Comment by coadler** [comment]
Actually, I lied. Your old project should be good now!

**Comment by npd1987** [comment]
Hey, thanks, it works now. I appreciate the quick help!
