### ISSUE TITLE
Terminal: outputting unicode characters doesn't work

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#208]
**Describe the bug**
When outputting a unicode character, an underscore is displayed instead.

**To Reproduce**
1. Open the IDE
2. Create a file with a unicode character (beware of #130)
3. `cat file`
4. See the underscore

**Expected behavior**
The unicode character should display.

**Screenshots**
![screenshot](https://awau.moe/36f18e.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 66.0.3359.170 (Developer Build) (64-bit)

**Additional context**
Reported via Zendesk `Ticket #1113`.

**Comment by jaymeramsay** [comment]
This is a known issue. A fix is ready and on the way soon.
