### ISSUE TITLE
Npm install failing with "Permission denied"

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#211]
**Describe the bug**
User is trying to install sass, but is receiving this error:
 ` "/usr/bin/node: line 3: /tmp/.coder-scl-main: Permission denied"`

**To Reproduce**
1. Open your IDE
2. run `npm install node-sass -g`
3. See error

**Expected behavior**
There shouldn't be a permissions error considering the way Coder is set up. Npm installs should complete without error.

**Desktop (please complete the following information):**
MacOS High Sierra
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Additional context**
Zendesk ticket ```1120```

**Comment by audibailey** [comment]
`chmod +x /tmp/.coder-scl-main` has no effect.

**Comment by levlaz** [comment]
The error appears to be coming from this script (which is `/usr/bin/node`), not necessarily from `node` or `npm` itself. 

```
  1 #!/bin/bash
  2                         rm -rf /tmp/.coder-scl-node && mkfifo /tmp/.coder-scl-node
  3                         echo node > /tmp/.coder-scl-main
  4                         re=^[0-9]+
  5                         while true
  6                         do
  7                                 response=$(cat /tmp/.coder-scl-node)
  8                                 if [[ $response == SCLPIPEEXIT* ]]; then
  9                                         stripped=${response:11}
 10                                         hash -d node 2>/dev/null || true
 11                                         if [[ $stripped =~ $re ]]; then
 12                                                 exit $stripped
 13                                         fi
 14                                         if [ -z "$stripped" ]; then
 15                                                 eval node "$@"
 16                                         else
 17                                                 eval $stripped
 18                                         fi
 19                                         exit $?
 20                                 else
 21                                         echo $response
 22                                 fi
 23                         done
 24
```

I am not actually 100% sure what this (node wrapper?) is supposed to accomplish.

The other interesting thing worth noting is that it looks like `node` itself lives in `/coder/bin/node` -- but npm install calls `/usr/bin/node` which points to this wrapper and then causes the failure.

**Comment by ammario** [comment]
Most of the language tooling is installed via our language mounting system. (Language mounts instantly install/upgrade, and take none of the user's disk)

@kylecarbs any chance the language mount wrapper could be causing this error?

**Comment by Multishifties** [comment]
Language mounting has since been removed. Users now self host and manage their own permissions.

@nol166 please close
