### ISSUE TITLE
Involuntary deleted files and directories

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#212]
**Describe the bug**
Users have reported their directories and files have been deleted when they open their project. Also, they have to reinstall dependencies. 

**To Reproduce**
Reproduction depends on the project. If you log into your project and no files or directories are present, please list your project name in the comments.

**Desktop (please complete the following information):**
 Mac High Sierra and Chrome 68

**Additional context**
```Zendesk tickets 1132, 1134```

**Comment by nol166** [comment]
fix in the pipeline
