### ISSUE TITLE
IDE: files can't be opened until container is restarted

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#214]
**Describe the bug**
After working on files and closing the IDE, the files cannot be accessed upon reopening the IDE until the container is restarted.

**To Reproduce**
1. Open the IDE
2. Create a file, put contents in the file, save the file
3. Close the browser tab
4. Open the IDE again
5. Click on the file in the file tree
6. Notice that it says the file does not exist
7. Restart the container
8. Open the IDE again and open the file
9. Notice that it works

I could not reproduce this.

**Expected behavior**
Files should be accessible after closing the IDE.

**Screenshots**
n/a

**Desktop:**
Browser: Google Chrome
Operating System: MacOSX

**Additional context**
Reported via Zendesk `Ticket #1125`.

**Comment by nol166** [comment]
Fix in the pipeline
