### ISSUE TITLE
IDE: switching browser tabs causes the terminal to hang

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#216]
**Describe the bug**
Switching browser tabs can cause the terminal tabs in the IDE to hang.

**To Reproduce**
1. Open the IDE
2. Open a terminal tab and type into it to verify that it's working
3. Switch browser tabs for a little while
4. Switch back to the Coder IDE tab
5. Try to type into the terminal tab
6. Notice that it's frozen

I'm unable to reproduce (I switch out of the Coder IDE all the time and this doesn't happen to me).

**Expected behavior**
The terminal tab should not freeze.

**Screenshots**
[Video](https://awau.moe/30e8c4.mp4)

**Desktop (please complete the following information):**
Browser: Google Chrome 70.0.3538.35
OS: Windows 10 1809

**Additional context**
Reported via Discord twice.

**Comment by nol166** [comment]
fix in the pipeline
