### ISSUE TITLE
IDE: JSON language server doesn't work properly

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#217]
**Describe the bug**
The IDE fails to start the nonexistent JSON language server on the container in a loop.

**To Reproduce**
1. Open the IDE
2. Open the dev tools for your browser and switch to console tab (make sure verbose statements are shown)
3. Create a JSON file (something.json)
4. Type in the file
5. Notice the massive warning loop

**Expected behavior**
The JSON language server should exist or the JSON language server should not be attempted to be loaded. The IDE should give up starting the language server after `x` failures.

**Screenshots**
![screenshot](https://awau.moe/d72fa2.png)

**Desktop:**
Browser: Google Chrome 70.0.3538.35
OS: Windows 10 1809

Screenshot is not from Chrome, but the same error was experienced by a user with the above specs.

**Additional context**
Reported via Discord twice.

**Comment by pokemonlover1234** [comment]
I've noticed that after about a minute this freezes the open terminal (Or my terminal was freezing for some other reason and it was just a coincidence that this was happening when my terminal was freezing)

**Comment by deansheather** [comment]
@pokemonlover1234 this is probably related to #216. Maybe these two issues are linked, but I don't think there's anything to suggest that at the moment.

**Comment by pokemonlover1234** [comment]
I had not been switching tabs, so I dont think that its #216

**Comment by pokemonlover1234** [comment]
After further testing, it does seem that it is the JSON file being open that causes the terminal to freeze after 10-15 seconds. It does not freeze if there is no JSON file open and with the JSON file open it freezes consistently

**Comment by nol166** [comment]
fix in the works
