### ISSUE TITLE
Auth: signing up via Google and picking a taken name doesn't return error or unlock submit button

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#218]
**Describe the bug**
Attempting to sign up with Google with a taken username causes the page to get stuck. No error is shown due to the username conflict, and the submit button gets stuck in it's disabled state.

**To Reproduce**
1. Sign up via Google
2. Confirm OAuth2 flow with Google
3. Select a username that is already taken (e.g. `deansheather`)
4. Notice that the page gets stuck

**Expected behavior**
An error message should appear telling the user that the username is taken, and the submit button should be enabled again.

**Screenshots**
n/a

**Desktop:**
 - OS: GNU/Linux 4.18.9_1 (Void Linux)
 - Browser: Chromium
 - Version: 66.0.3359.170 (Developer Build) (64-bit)

**Additional context**
Reported via Discord.

**Comment by nol166** [comment]
fix in the pipeline
