### ISSUE TITLE
QA: Terminal stops accepting inputs. New terminal needs to be opened.

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#219]
Oct 3, 2018 at 10:24:06 AM
**Describe the bug**
A user has reported that when using the Coder IDE, the terminal will stop responding causing them to have to open another instance of the terminal. This significantly impacts workflow.

**To Reproduce**
Investigating

**Expected behavior**
The terminal can be used until it is closed.

**Desktop:**
Windows/Chrome

**Zendesk**
1174

**Comment by pokemonlover1234** [comment]
I noticed that the terminal kept freezing for me if I have a JSON file open. Could be related to #217

**Comment by nol166** [comment]
@pokemonlover1234 I think you might be onto something. I am testing now.

**Comment by nol166** [comment]
@pokemonlover1234 Do you know long after working with large JSON files that the terminal stops responding?

**Comment by nol166** [comment]
@pokemonlover1234 Nvm, I was just able to replicate. Thank you!

**Comment by pokemonlover1234** [comment]
@nol166 it doesnt even have to be large json files

**Comment by VanWeapon** [comment]
I have had this issue also, using Firefox. Often happens after switching tabs as well but can just happen randomly.

**Comment by nol166** [comment]
` 1214` `1210`

**Comment by filipeglfw** [comment]
I am also experiencing this but I never opened a JSON file. I only edited a HTML and a CSS file.
Windows 10/Chrome 70

**Comment by nol166** [comment]
fix in the pipeline
