### ISSUE TITLE
IDE: JS Errors on Reload 

### ISSUE THREAD

**Issue by jaentwistle** [codercom/bugs#22]

**Comment by jaentwistle** [comment]
Submitted via Zendesk 
"When I created a container with a single Go file and then reloaded in my browser, I saw some JS errors:

bundle.js:2213 Uncaught (in promise) TypeError: Cannot read property 'watch' of undefined 
at bundle.js:2213 
at Array.map (<anonymous"

**Comment by jaymeramsay** [comment]
This appears to be resolved.
