### ISSUE TITLE
IDE: creating duplicate folder in Explorer causes browser to use lots of CPU

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#220]
**Describe the bug**
Creating a duplicate folder in the Explorer causes the CPU usage to go up incredibly and the browser to freeze.

**To Reproduce**
1. Open the IDE
2. Create a folder in the file explorer named `src`
3. Create a folder in the same directory also called `src`
4. Notice that nothing pops up
5. Notice that CPU usage goes up and the browser freezes
6. Kill the browser

Unable to reproduce. I believe this could be related to Firefox Quantum specifically which I don't have installed (I'm running Firefox ESR).

**Expected behavior**
No excessive CPU usage, no frozen browser, and an alert to show that the folder already exists (or maybe duplicate folder creations could be silently ignored).

**Screenshots**
n/a

**Desktop**
 - OS: macOS 10.12.6
 - Browser: Firefox Quantum v62.0.3

**Additional context**
Reported via Discord. User says they have experienced it multiple times before. I believe I've seen a ticket with an issue similar to this before, but it got closed due to no response from the user.

**Comment by pokemonlover1234** [comment]
I was able to reproduce once on firefox quantum with windows 10, however I haven't been able to do so again. Also, my browser did not freeze. Every other time I try the steps, it gives the message that says that a folder already exists

**Comment by deansheather** [comment]
Maybe there's something wrong with the steps I wrote, I'll ask the reporter to try following the steps in this bug report and see if they can reproduce it.

**Comment by deansheather** [comment]
Reporter says that the steps should be accurate and they can't reproduce it again. Maybe there's some other factor that causes this issue.

**Comment by pokemonlover1234** [comment]
I'll do some more testing

**Comment by nol166** [comment]
fix in the pipeline
