### ISSUE TITLE
IDE: settings edit button menus don't disappear when you click away from them

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#221]
**Describe the bug**
Clicking away from one of the edit menus in the IDE settings doesn't make the menu disappear as you'd expect. To make the menu disappear you must click an option.

**To Reproduce**
1. Open the IDE
2. Open the IDE settings (File > Settings)
3. Click on one of the white edit buttons beside an option
4. Click away from the menu
5. Notice that it doesn't disappear
6. Click an option on the menu
7. Notice that it disappears

**Expected behavior**
The context menu should disappear when you click away from it. Also the white box should probably not be filled in white and have a pencil/edit icon instead.

**Screenshots**
[Video](https://awau.moe/aacd26.webm)

**Desktop:**
OS: Linux
Browser: Chromium
Version: 66.0.3359.170 (Developer Build) (64-bit)

**Additional context**
Reported via Zendesk `Ticket #1204`.

**Comment by nol166** [comment]
fix in the works
