### ISSUE TITLE
IDE: using Ctrl+Arrow for word navigation doesn't work on macOS

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#222]
**Describe the bug**
Ctrl+Arrow doesn't work for navigating between words on macOS, as this keybind is used by the system to switch between desktops/workspaces.

**To Reproduce**
1. Use a Mac
2. Open the IDE
3. Open a file with words in it
4. Use Ctrl+Right to navigate between words
5. Notice that it doesn't work, and switches workspaces in macOS instead
6. Try on a Windows/Linux machine
7. Notice that it navigates between words as expected

**Expected behavior**
The Ctrl+Arrow keybinding that is used on Windows/Linux systems should be changed to Alt+Arrow on Mac systems or should be configurable in IDE settings.

**Screenshots**
n/a

**Desktop:**
Browser: Google Chrome
Operating System: macOS

**Additional context**
Reported via Zendesk `Ticket #1203`. Elevated from feature request codercom/features#125.

**Comment by nol166** [comment]
fix in the works
