### ISSUE TITLE
Support MongoDB

### ISSUE THREAD

**Issue by chjo-hb** [codercom/bugs#223]
**Describe the bug**

**To Reproduce**
1. Install MongoDB according to official instructions.
2. Try adding it as service.
3. Re-Install MongoDB according to inofficial instructions to get it running manually by giving the command 'mongod'.
4. Command 'service mongod start' returns 'mongod: unrecognized service'.

**Expected behavior**
Command 'mongo' shoudl be available at command prompt.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
One can install MongoDB, but it needs a way to be added to services and boot sequence to start automatically in the container.

**Comment by nol166** [comment]
@chjo-hb Given the way our containers turn on and off there isn't a really good solution to this problem. I would recommend modifying your bashrc file, but even then it's not great. I will let our team know that users need a way to run things on boot and see if we can get this implemented

**Comment by nol166** [comment]
Moving this to /features
