### ISSUE TITLE
IDE: changing keyboard shortcuts doesn't work

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#226]
**Describe the bug**
When you change a keyboard shortcut, the keyboard shortcut buffer freezes.

**To Reproduce**
1. Open the IDE
2. Open the Keyboard Shortcuts preferences
3. Change the save shortcut to something like Ctrl+Numpad1
4. Notice how it freezes for a second
5. Notice how it doesn't write the changes

**Expected behavior**
The keyboard shortcuts menu should work properly.

**Screenshots**
n/a

**Desktop:**
 - OS: Linux
 - Browser: Chromium
 - Version: 69.0.3497.100 (Developer Build) (64-bit)

**Additional context**
Originally reported via Discord.

**Comment by jaymeramsay** [comment]
I'm currently unable to reproduce this with Linux and Mac.

**Comment by kylecarbs** [comment]
Should be fixed :confetti_ball:
