### ISSUE TITLE
Ctrl + S opens save window in windows and doesn't save file to disk

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#229]
**Describe the bug**
When you try to save the contents of your file in Windows by using `Ctrl + S`, it can't save the file contents to disk. It opens a Save As window. Catting the file shows no data.

**To Reproduce**
1. Go to Projects page
2. Open the IDE
3. Open a file and alter it
4. press `Ctrl + S`

**Expected behavior**
`Ctrl + s` saves the changes to disk. Also, the dot in the tab disappears, showing the save was successful.

**Screenshots**
![screen shot 2018-11-06 at 2 11 23 pm](https://user-images.githubusercontent.com/28520845/48091064-457afa00-e1ce-11e8-9887-99e5ea169aff.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 72

```zendesk 1321```
```zendesk 1333```

**Comment by shahidcodes** [comment]
For now we can use -
`ALT+SHIFT+F` to open `FILE` dropdown and then `S` to save.

**Comment by kylecarbs** [comment]
Should be fixed :confetti_ball:
