### ISSUE TITLE
Project Dashboard: Date Failing to Display Correctly

### ISSUE THREAD

**Issue by jaentwistle** [codercom/bugs#23]
Submitted Via Zendesk 
"After creating a project the last opened date shows as "Mon Jan 01 0001""

**Comment by nol166** [comment]
This issue has been fixed.

**Comment by deansheather** [comment]
@nol166 Seems broken again:
![screenshot](https://owo.whats-th.is/f4d386.png)

**Comment by deansheather** [comment]
Reported again by another user in Discord.

**Comment by ammario** [comment]
@coadler is working on this fix in the backend.

**Comment by ammario** [comment]
Nvm. The frontend should display `Never` instead.

**Comment by nol166** [comment]
zendesk `494`

**Comment by deansheather** [comment]
Zendesk `Ticket #579`.

**Comment by nol166** [comment]
Zendesk `606`

**Comment by jaymeramsay** [comment]
related issue: https://github.com/codercom/features/issues/74

**Comment by nol166** [comment]
zendesk `897`

**Comment by deansheather** [comment]
Zendesk `Ticket #906`.

**Comment by jaymeramsay** [comment]
Zendesk `1019`

**Comment by jaymeramsay** [comment]
Zendesk `1085`
