### ISSUE TITLE
Full screen mode isn't working in the IDE

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#230]
**Describe the bug**
A user tried to use full-screen mode in the ide and nothing happened. It was non-responsive.

**To Reproduce**
1. Go to projects page
2. Open the IDE of one of them
3. Try `ctrl + cmd + F`
4. Or, navigate to View > Appearance > Full Screen Mode

**Expected behavior**
Coder to expand to full screen

**Desktop (please complete the following information):**
 - OS: Mac and Linux
 - Browser Chrome and Firefox for both

```zendesk ticket 1325```

**Comment by kylecarbs** [comment]
Fixed :confetti_ball:
