### ISSUE TITLE
CTRL+` doesn't open terminal window

### ISSUE THREAD

**Issue by shahidcodes** [codercom/bugs#231]
**Describe the bug**
CTRL+` doesn't open terminal window. We have to spawn a new terminal everytime we've to see the terminal window

**To Reproduce**
1. Go to 'TERMINAL'
2. Click on 'NEW TERMINAL'
3. Run anything in terminal and close it (click X button)
4. Now CTRL+` does not open it. To see the opened terminal do STEP1,2 again and switch the terminal from dropdown

**Expected behavior**
CTRL+` should show the TERMINAL view

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 70

**Comment by jaymeramsay** [comment]
You're using Windows, correct? I'm currently unable to reproduce this issue. To cover all of our bases, do you have that keybind already bound to something else? What happens when you customize the terminal keybind?

**Comment by kylecarbs** [comment]
Should be fixed, but not 100%. Could you verify?

**Comment by leoek** [comment]
@shahidcodes what is your current keyboard layout? If it is not the us layout, #246 probably applies to you too and you can try to use ` ctrl+shift+<the key below esc, whatever it is in your layout> ` until #246 is fixed.

**Comment by shahidcodes** [comment]
@leoek My layout en-US. Same as this image from #246 
![](https://user-images.githubusercontent.com/9424038/48452775-e2322e80-e7b0-11e8-86f4-8d85d8bda1cd.jpg) and now it works. 😊
