### ISSUE TITLE
Flags don't appear for countries in phone number selection box

### ISSUE THREAD

**Issue by NGTmeaty** [codercom/bugs#232]
**Describe the bug**
Flags don't appear in the drop-down or the box next to the original phone number showing your country code, and a blank white box. 

**To Reproduce**
1. Go to your [profile/account settings.](https://coder.com/settings/my-account)
2. Click on country selector with your country code.
3. See error

**Expected behavior**
All flags should appear in the drop down and the flag of your country in the little "preview" box.

**Screenshots**
![screenshot](https://owo.whats-th.is/4087c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.77

**Additional context**

**Comment by deansheather** [comment]
Unable to reproduce using Chromium on Linux.
![screenshot](https://awau.moe/b67211.png)

**Comment by deansheather** [comment]
Zendesk `Ticket #1413`.

**Comment by NGTmeaty** [comment]
Still can reproduce on windows, will check my chromebook. May be OS related.

**Comment by Multishifties** [comment]
This settings page with this component has since been removed from our website.

@nol166 please close
