### ISSUE TITLE
Some parts of the IDE aren't themed

### ISSUE THREAD

**Issue by Vap0r1ze** [codercom/bugs#239]
**Describe the bug**
Themes only apply to the current file and the terminal

**To Reproduce**
1. Install a theme
2. Use it

**Expected behavior**
The whole IDE is themed

**Screenshots**
![image](https://user-images.githubusercontent.com/20448879/48292691-5b482380-e449-11e8-9bf3-99ec86d6d76a.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 70

**Comment by kylecarbs** [comment]
Are you sure this isn't theme-based? I'm unable to reproduce.

**Comment by Multishifties** [comment]
Just tested several themes within the IDE, everything appears to be working as it should be.
That said, I did see some themes that had imitations/fakes. There are at least two "Atom one dark theme" themes in the marketplace. The original one and another one someone created (probably hoping that other people would download it by accident)

**Comment by Multishifties** [comment]
No longer relevant since release of `code-server`

@nol166 please close
