### ISSUE TITLE
Settings: display name input box is really small

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#242]
**Describe the bug**
The display name input box on the settings page is really small and confuses users when they try to focus it.

**To Reproduce**
1. Go to [My Account](https://coder.com/settings/my-account)
2. Click the center of the area where you would expect the Display Name input box to be
3. Notice that it doesn't focus an input box
4. Click right underneath the word "Display"
5. Notice that the input box is focused and is much smaller than expected

**Expected behavior**
The input box should span the width of the column.

**Screenshots**
![screenshot](https://awau.moe/fba629.png)

**Desktop:**
 - OS: Linux
 - Browser: Chromium Version 69.0.3497.100

**Additional context**
Originally reported via Zendesk `Ticket #1407`.

**Comment by Multishifties** [comment]
Account page has since been removed.

@nol166 please close.
