### ISSUE TITLE
[Suggestion] Please add option to edit single files

### ISSUE THREAD

**Issue by weitzhandler** [codercom/bugs#244]
Hi,

Please add option to use codercom without having to create projects, but rather as an interpreter or an interactive console for C#, JAVA etc., much like [dotnetfiddle](https://dotnetfiddle.net).

Thanks a lot!

**Comment by NGTmeaty** [comment]
This should go [here.](https://github.com/codercom/features)

**Comment by weitzhandler** [comment]
[Done](https://github.com/codercom/features/issues/142)

**Comment by NGTmeaty** [comment]
Thanks.

**Comment by weitzhandler** [comment]
WOW, almost like a chat!
