### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by codemzy** [codercom/bugs#247]
**Describe the bug**
I understand that to upload files you should be able to drag and drop. However, while I get the 'plus' icon when I drag a file, nothing gets uploaded when I drop it.

**To Reproduce**
1. Go to Project
2. Click on Open in VS Code
3. Drag File to Explorer
4. Drop and see nothing happens

**Expected behavior**
Expected file to be uploaded.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by Multishifties** [comment]
@codemzy Good catch! We used to support this behavior with our previous IDE (v0.1.4). I'll forward this to the rest of the Front End team!

Thanks for helping us keep Coder awesome and user friendly! We'll notify you when we fix this.

**Comment by Multishifties** [comment]
UPADTE: We've re-added this functionality on our develop network. This should be patched when version 0.2.1 rolls out. (Can't give you an ETA on when that will be, but it shouldn't be too long considering current version is 0.2.0)

**Comment by deansheather** [comment]
Zendesk `Ticket #1524`.

**Comment by Multishifties** [comment]
As an update to this. Drag and drop in the IDE now works for most non-binary files! (We're still working on getting image files working correctly)

**Comment by Multishifties** [comment]
@nol166 you can probably close this issue now. I imagine the 0.3.0 binary solves these issues. (I was unable to re-create this on Prod)
