### ISSUE TITLE
Favicon doesn't appear correctly on certain pages

### ISSUE THREAD

**Issue by NGTmeaty** [codercom/bugs#248]
**Describe the bug**
The Favicon doesn't appear correctly on some pages and shows a google logo. Seems to reply with the 404 page.

**To Reproduce**
1. Go to home page
2. See [error](https://owo.whats-th.is/39319a.png)

**Expected behavior**
You should see a Coder favicon, rather than google. 

**Screenshots**
https://owo.whats-th.is/39319a.png
https://owo.whats-th.is/2e1866.png
https://owo.whats-th.is/0f60d7.png
https://owo.whats-th.is/fafd03.png

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Chrome
 - Version 70.0.3538.102

**Additional context**

It happened on other pages, rather than just the home page, but can't replicate anymore.

**Comment by Multishifties** [comment]
This was an issue that I resolved a few weeks ago. This should no longer occur.

**Comment by nol166** [comment]
Resolved, closing
