### ISSUE TITLE
Sing up process doesn't work with Vivaldi browser

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#256]
**Describe the bug**
A user has reported that signing up or logging into an existing account isn't possible when using the Vivald browser

**To Reproduce**
Not able to replicate in MacOS. Attempting to replicate using windows.

**Expected behavior**
Signup is possible with as many browsers as possible

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Vivaldi: 1.10.867.38

**Comment by grwag** [comment]
The version of vivaldi that I used was fairly old (that's what you get for never closing any tabs I guess...). After updating the browser signing in and signup works well.

**Comment by nol166** [comment]
Issue caused by the outdated browser. Closing.
