### ISSUE TITLE
Frequent file saving issues

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#257]
**Describe the bug**
Several users have reported issues of files not saving. Some users have noted that they need to turn off the container and return to the project in order to get things working again. The problem is by that point the changes are gone with no way to recover them.

**To Reproduce**
testing to replicate

**Expected behavior**
Files save properly. No data loss.

**Additional context**
zendesk `1498`

**Comment by rdbauer** [comment]
To add additional info, I have experienced this too but I have seen that it shows as saved and the server automatically re-compiles even. The change is not transferred to the browser and when I close the file and reopen, it isn't saved as described above. Hope this helps.

**Comment by ammario** [comment]
@kylecarbs has it been figured out whether this issue is on the frontend or the backend?

**Comment by kylecarbs** [comment]
@ammario Seems likely its a frontend issue.

**Comment by deansheather** [comment]
Zendesk `#1580`

**Comment by paul-blundell** [comment]
After playing around with Coder some more it looks like this issue happens for me after I rename a file.

**Comment by deansheather** [comment]
A user in Discord says that after reloading the IDE the changes were displayed in the editor but weren't persisted to disk.

**Comment by nol166** [comment]
`1583`

**Comment by tetious** [comment]
I can't seem to get ANY files to save unless I delete them from the terminal first. I've tried restarting my container, creating a new project, and a few other things without success.

**Comment by nol166** [comment]
@tetious We have an internal issue regarding this bug that is currently set as a high priority. Will updated this issue as I receive more information.

**Comment by deansheather** [comment]
`1833`

**Comment by nol166** [comment]
`1846`

**Comment by nol166** [comment]
`1858`

**Comment by deansheather** [comment]
Another user on Zendesk with this problem, solved by deleting the file via `rm`.

**Comment by nol166** [comment]
`1888`

**Comment by nol166** [comment]
A fix has been pushed for this issue. I will leave this open in case you guys run into anything for the rest of the week.

**Comment by Multishifties** [comment]
Considering this issue has been quiet since the fix was pushed. I believe it's safe to close this.

@nol166 please close
