### ISSUE TITLE
IDE: output panel is always empty

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#259]
**Describe the bug**
Nothing shows up in the output panel ever, even when using it for things like [Code Runner](https://github.com/formulahendry/vscode-code-runner).

**To Reproduce**
1. Open the IDE
2. Open the output panel (View > Output or `Ctrl+K Ctrl+H`)
3. Notice that it's empty
4. Change between all tabs and notice that it's still empty

**Expected behavior**
The expected output should be shown.

**Screenshots**
n/a

**Desktop:**
 - OS: Windows
 - Browser: Chromium
 - Version: 70.0.3538.102

**Additional context**
Reported via Discord.

**Comment by marcorivm** [comment]
When looking at developer tools output after trying to view the output panel it throws the following error, which seems to indicate log files are not being created:
```
  ERR File not found (file:///tmp/logs/20181127T194326/output_1_20181127T194330/extensions.log): Error: File not found (file:///tmp/logs/20181127T194326/output_1_20181127T194330/extensions.log)
    at new t (https://coder.com/181/ide/1-97a28b.bundle.js:1:166916)
    at https://coder.com/181/ide/1-97a28b.bundle.js:1:2628227
    at Object.R [as _notify] (https://coder.com/181/ide/1-97a28b.bundle.js:1:25721)
    at Object.enter (https://coder.com/181/ide/1-97a28b.bundle.js:1:22784)
    at n.Class.derive._oncancel._run (https://coder.com/181/ide/1-97a28b.bundle.js:1:24139)
    at n.Class.derive._oncancel._error (https://coder.com/181/ide/1-97a28b.bundle.js:1:23656)
    at https://coder.com/181/ide/1-97a28b.bundle.js:1:66834
    at https://coder.com/181/ide/1-97a28b.bundle.js:1:493391
    at https://coder.com/181/ide/1-97a28b.bundle.js:1:223743
    at Array.forEach (<anonymous>)
```
/tmp/logs folder exists but is empty.
I tried doing a search for the extensions.log file on the system but couldn't find it

**Comment by kylecarbs** [comment]
Fixed :confetti_ball:
