### ISSUE TITLE
Google/Github sign in - infinite loop

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#262]
Nov 26, 2018 at 3:56:09 PM
**Describe the bug**
When attempting to sign into an already created account using the Github or Google log in buttons, it appears to send the user into an infinite loop rendering them not able to get past the log in screen. 

**Environment**
Production

**To Reproduce**
1. Visit coder.com/signup
2. Create an account with Google
3. Log out
4. Go to coder.com/login and choose log in with Google
5. Choose your coder account
6. Notice that you get brought back to /login 

**Expected behavior**
Should direct to /projects

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 70

**Zendesk**
`1518`

**Comment by memelaser** [comment]
This is now different.
On Chrome, after using one of those buttons, you just get a screen with a 
{}
on it, and you have to go back to coder.com and hit login, and then it directs you to ide.coder.com

**Comment by nol166** [comment]
This has been fixed, tested it yesterday
