### ISSUE TITLE
Odd font formatting in the terminal

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#263]
Nov 26, 2018 at 4:23:30 PM
**Describe the bug**
A user has reported that the terminal font looks odd after the initial load. This seems to be reminiscent of a bug we had in v0.1. The user mentioned they were able to resolve the issue by manually changing the default font properties in settings.

**Environment**
Prod

**To Reproduce**
1. Use ubuntu 18 and chrome
2. Launch the IDE 

**Expected behavior**
Normal formatting

**Desktop:**
 - OS: Ubuntu 18
 - Browser: Chrome

**Zendesk**
`1525`

**Comment by Multishifties** [comment]
I believe this is safe to close if there have been no reports of this in the past 4 months.

@nol166 please close
