### ISSUE TITLE
Settings sync extension doesn't work properly

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#264]
Nov 27, 2018 at 5:51:41 PM
**Describe the bug**
Using the settings sync extension to sync settings and extensions doesn't seem to work with VSCode cloud. The settings appear to download but the settings are stored in a different location than VSCode local.

**To Reproduce** 
1. Go to 'coder.com' install sync extension normally
2. Try downloading the settings and the file will download to ~/.config/User/settings.json
3. VSCode settings won't reflect the downloaded settings and extensions won't install

**Expected behavior**
Settings download and sync properly

**Additional information**
There is an open issue on the GitHub for the actual extension regarding coder.com. For reference[ click here](https://github.com/shanalikhan/code-settings-sync/issues/714)

**Comment by deansheather** [comment]
shanalikhan/code-settings-sync#720
