### ISSUE TITLE
Sign up using Github is a bit confusing

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#265]
**Describe the bug**
A user has reported that when signing up using Github it is a bit confusing. The flow is as such:

If you are signed into Github in your current browser session, visit coder.com/signup and click the "Sign up with Github" button the following happens:

You are taken from the normal sign up form to a screen that says "Almost done" where you can choose your username and enter your phone number. Because the user has offered no indication of what GitHub account they want to use or even a reminder that they are logged in to GitHub, the result is very jarring and rather confusing. The user mentioned that it wasn't clear if they had accidentally created two accounts

**To Reproduce**
1. Go github.com and make sure you are signed in
2. Go to coder.com/signup
3. Click sign up with GitHub
4. Notice that without selecting your GitHub account or providing any information whatsoever, you are taken to the "almost done" screen.

**Expected behavior**
Maybe we could say something like "Singed in with {github username}" Continue creating your account.

**Screenshots**
![screen shot 2018-11-28 at 11 03 56 am](https://user-images.githubusercontent.com/5651438/49168545-52869700-f2fd-11e8-8fc9-7a57ea6fc91a.png)

**Additional context**
Zendesk `1546`

**Comment by Multishifties** [comment]
@nol166 close issue plz? (You closed the mirror of this issue on `frontend`)
