### ISSUE TITLE
Unexpected behavior when working with collaborators 

### ISSUE THREAD

**Issue by pokemonlover1234** [codercom/bugs#269]
**Describe the bug**
Cannot save files if files are open by more than one person and differences in what they see.
**To Reproduce**
1. Have more than one collaborator open the same file
2. Make edits
3. Try to save
4. Fail to save
5. Notice differences in content of file between each collaborator.

**Expected behavior**
Files are savable and all collaborators see the same content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.1 (With Firefox) and Windows 10 (With Chrome)
 - Browser Firefox and Chrome
 - Version Firefox 63 and Chrome 70

**Additional context**
Reported by a user via discord.

**Comment by Multishifties** [comment]
Collaboration has been removed.

@nol166 please close
