### ISSUE TITLE
PowerShell extension for VSCode is not starting up

### ISSUE THREAD

**Issue by TylerLeonhardt** [codercom/bugs#270]
Hi everyone! I'm a maintainer of the PowerShell extension for VSCode 👋 

We've got a lot of PowerShell users that really want to use Coder with the PowerShell extension 😀

**Describe the bug**
There currently seems to be some limitations on the Coder-side that's preventing the PowerShell extension from loading so I'd love to work with you to get it solved. 👍 

Architecturally, the PowerShell extension is a bit different than normal LSP extensions. Most speak to each other via stdio... But PowerShell uses Named Pipes (or Unix domain sockets on Linux + macOS) to enable certain additional features.

If I had to guess, I would guess that it could be related to creating those pipes, but I don't know enough about Coder to be certain. 

**To Reproduce**
1. Install PowerShell in the container - several users on Twitter have been able to accomplish this: https://twitter.com/sstranger/status/1069504796401520640?s=19
2. Install the PowerShell extension 
3. Open a PowerShell file
4. The PowerShell extension never finishes starting up

**Expected behavior**
The PowerShell extension works

**Additional context**

We have some logs from the PowerShell extension:

> 2018-12-3 16:54:50 [NORMAL] - Language server starting --
2018-12-3 16:54:50 [NORMAL] -     exe: /usr/bin/pwsh
2018-12-3 16:54:50 [NORMAL] -     args: /root/vscode/extensions/ms-vscode.powershell-1.9.0/modules/PowerShellEditorServices/Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.9.0'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/root/vscode/extensions/ms-vscode.powershell-1.9.0/modules'-EnableConsoleRepl -LogLevel 'Normal' -LogPath '/root/vscode/extensions/ms-vscode.powershell-1.9.0/logs/1543856090-1/EditorServices.log' -SessionDetailsPath '/root/vscode/extensions/ms-vscode.powershell-1.9.0/sessions/PSES-VSCode-undefined-971397' -FeatureFlags @()
2018-12-3 16:54:51 [NORMAL] - powershell.exe terminated or terminal UI was closed

```
2018-12-3 16:56:33 [NORMAL] - Language server startup failed.
2018-12-3 16:56:33 [ERROR] - Timed out waiting for session file to appear.
2018-12-3 16:56:33 [ERROR] - The language service could not be started:
2018-12-3 16:56:50 [NORMAL] - Language server startup failed.
2018-12-3 16:56:50 [ERROR] - The language service could not be started:
2018-12-3 16:56:50 [ERROR] - Timed out waiting for session file to appear.
```

Note the session details file saying `undefined`. I'll work on getting more logs but you folks would have the insight on the container environment.

**Comment by nol166** [comment]
@TylerLeonhardt We will get this fixed. Sorry, it didn't work out of the gate.

**Comment by TylerLeonhardt** [comment]
Some people on Discord think that it's related to how you folks changed the vscode terminal APIs

**Comment by TylerLeonhardt** [comment]
Just as an FYI, the PowerShell community has been actively playing with coder.com 😄 

https://twitter.com/sstranger/status/1069504796401520640

**Comment by kylecarbs** [comment]
It appears the language server fails to start with this output:
```
The specified module 'PowerShellEditorServices' was not loaded because no valid module file was found in any module directory.
```
Interestingly, installing [PowerShellEditorServices](https://github.com/PowerShell/PowerShellEditorServices) manually did not fix the issue.

Will look into this further :thinking:

**Comment by TylerLeonhardt** [comment]
Interesting... I wonder if this could mean the BundledModulePath is not being set correctly in the coder environment.

Basically we pass in this variable that we get from the settings that has a default value:
https://github.com/PowerShell/vscode-powershell/blob/master/src/session.ts#L151

to the Start-EditorServices.ps1 that is executed using vscode terminals:
https://github.com/PowerShell/vscode-powershell/blob/master/src/process.ts#L103

In Start-EditorServices.ps1, we append that value to the environment variable PSModulePath (if you're not a PowerShell user, this works similar to that of regular environment variable PATH)

https://github.com/PowerShell/PowerShellEditorServices/blob/master/module/PowerShellEditorServices/Start-EditorServices.ps1#L327

**Comment by TylerLeonhardt** [comment]
the default value is here:
https://github.com/PowerShell/vscode-powershell/blob/master/src/settings.ts#L150

**Comment by cawwot** [comment]
Currently the extension logs look like this on Windows 10, Firefox 60.3.0esr (64-bit):

```
2019-2-1 12:12:43 [NORMAL] - Visual Studio Code v1.28.0 64-bit
2019-2-1 12:12:43 [NORMAL] - PowerShell Extension v1.9.0
2019-2-1 12:12:43 [NORMAL] - Operating System: Linux 64-bit
2019-2-1 12:12:43 [ERROR] - Error while attempting to require /./node_modules.asar/vscode-textmate
2019-2-1 12:12:43 [ERROR] - Error: Cannot find module '/./node_modules.asar/vscode-textmate'
2019-2-1 12:12:43 [NORMAL] - Path specified by 'powerShellExePath' setting - '' - not found, reverting to default PowerShell path.
2019-2-1 12:12:43 [NORMAL] - Language server starting --
2019-2-1 12:12:43 [NORMAL] -     exe: /usr/bin/pwsh
2019-2-1 12:12:43 [NORMAL] -     args: /root/vscode/extensions/ms-vscode.powershell-1.9.0/modules/PowerShellEditorServices/Start-EditorServices.ps1 -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '1.9.0'-AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath '/root/vscode/extensions/ms-vscode.powershell-1.9.0/modules'-EnableConsoleRepl -LogLevel 'Normal' -LogPath '/root/vscode/extensions/ms-vscode.powershell-1.9.0/logs/1549023163-1/EditorServices.log' -SessionDetailsPath '/root/vscode/extensions/ms-vscode.powershell-1.9.0/sessions/PSES-VSCode-undefined-553461' -FeatureFlags @()
2019-2-1 12:12:43 [NORMAL] - Syntax Folding Provider registered
2019-2-1 12:12:43 [NORMAL] - powershell.exe terminated or terminal UI was closed
2019-2-1 12:14:43 [NORMAL] - Language server startup failed.
2019-2-1 12:14:43 [ERROR] - The language service could not be started: 
2019-2-1 12:14:43 [ERROR] - Timed out waiting for session file to appear.
```
I am very excited to see this fixed; PowerShell in coder is an amazing combination!

**Comment by foresthoffman** [comment]
Howdy @TylerLeonhardt, I think I may have a good step forward to a solution. I made some changes to the built extension files PowerShell v1.11.0 which got the integrated console working! It seems that v1.11.0 also fixes the "PowerShellEditorServies" issue that some of us were seeing.

### Steps to recreate
1. Install PowerShell v1.9.0.
2. Reload.
3. Open a terminal and run the following:
```bash
cd /root/vscode/extensions
wget -q https://storage.googleapis.com/coder-production-extensions/ms-vscode.PowerShell/1.11.0/Microsoft.VisualStudio.Services.VSIXPackage
tar xf Microsoft.VisualStudio.Services.VSIXPackage extension
mv extension ms-vscode.powershell-1.11.0
cd ms-vscode.powershell-1.11.0/out/src
grep -nE '\-FeatureFlags @' process.js | awk -F':' '{ print $1 }' | xargs -I '%' sed -i '%s/.*/(featureFlags ? `-FeatureFlags ${featureFlags}` : "");/' process.js
grep -nE '&.*PowerShellProcess\.escapeSingleQuotes\(' process.js | awk -F':' '{ print $1 }' | xargs -I '%' sed -i '%s/"\& '"'"'"/"\& " + powerShellExePath + " '"'"'"/' process.js
grep -nE 'let powerShellExePath = this.exePath;' process.js | awk -F':' '{ print $1 }' | xargs -I '%' sed -i '%s/.*//' process.js
grep -nE '&.*PowerShellProcess\.escapeSingleQuotes\(' process.js | awk -F':' '{ print $1 }' | xargs -I '%' sed -i '%ilet powerShellExePath = this.exePath;' process.js
grep -nE '`\-AdditionalModules @\('"'"'PowerShellEditorServices.VSCode'"'"'\) ` +' session.js | awk -F':' '{ print $1 }' | xargs -I '%' sed -i '%s/.*/`-AdditionalModules '"'"'PowerShellEditorServices.VSCode'"'"' ` +/' session.js
cd /root/vscode/extensions
rm -rf cd /root/vscode/extensions/ms-vscode.powershell-1.9.0
```
4. Disable the PowerShell extension and reload.
5. Check the PowerShell extension version in the Extensions View, it should read `1.11.0`.
_If it doesn't_, run: `cat /root/vscode/extensions/.obsolete`. If the file references `ms-vscode.powershell-1.11.0`, exchange the version number for `1.9.0`. The command below should do it. Then disable the extension one more time, and reload.
```bash
sed -i 's/1\.11\.0/1\.9\.0/' /root/vscode/extensions/.obsolete
```
6. Make sure that the `pwsh` executable is installed on your container and is accessible via your `PATH`.

Here's a commit with the [changes](https://github.com/foresthoffman/vscode-powershell/commit/7136c086d444c4684f233938f15a8121b1aafe6c) to the extension source. I doubt that they are prestine changes, seeing as I don't really have any context, but hopefully this will help figure out what is causing the conflict.

**Comment by TylerLeonhardt** [comment]
Thanks @foresthoffman! This is great to see I'll give it a look 😄

Quick question. Why did you need to install 1.9.0 at all?

**Comment by nol166** [comment]
That was the most recent build in our extension database.

**Comment by TylerLeonhardt** [comment]
Thanks for that @nol166 😊makes sense.

[I commented on the changes](https://github.com/foresthoffman/vscode-powershell/commit/7136c086d444c4684f233938f15a8121b1aafe6c#r32346144). It's odd to me that the fix involved having PowerShell call PowerShell instead of just the terminal api calling PowerShell

**Comment by TylerLeonhardt** [comment]
@foresthoffman do you think you could try using this vsix? It has https://github.com/PowerShell/vscode-powershell/pull/1774 in it:

[PowerShell-insiders.vsix.zip](https://github.com/codercom/bugs/files/2906945/PowerShell-insiders.vsix.zip)

**Comment by foresthoffman** [comment]
@TylerLeonhardt That works for me! 🎉
