### ISSUE TITLE
Store: can't purchase plans on Firefox and Safari

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#273]
**Describe the bug**
On Firefox and Safari the Payment Method selection box never appears when attempting to purchase a plan.

Additionally, the price on the payment selection screen is displayed without a period (compare the screenshots below).

In Firefox, there's an error in the console that doesn't appear in Chrome's console:
```
SyntaxError: invalid regexp group in checkout.js
```

**To Reproduce**
1. Open the Store
2. Select any plan
3. Notice that the payment method selection box never appears
4. Repeat steps 1-3 in Chromium
5. Notice that the payment selection box does appear

**Expected behavior**
The payment selection box should appear and work properly.

**Screenshots**
Firefox: this is **not expected** behavior
![firefox](https://awau.moe/01cfce.png)

Chrome: this is **expected** behavior
![chrome](https://awau.moe/9968eb.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox Quantum 63.0.3

**Additional context**
Reported via Zendesk `Ticket #1609`. I tested this on Firefox but not on Safari.

**Comment by deansheather** [comment]
Also there's no page `<title>` on `/checkout`.

**Comment by Multishifties** [comment]
Appears Fixed. I believe this was fixed with https://github.com/codercom/frontend/commit/b7dfbae791170f8c2c882b4bf562c3339a1efd50

As for the title in checkout, I've gone through and checked all our pages. All pages should now have Title tags when https://github.com/codercom/frontend/pull/156 is merged.

**Comment by Multishifties** [comment]
This issue is ready to be closed

**Comment by nol166** [comment]
Fixed
