### ISSUE TITLE
Users getting kicked back to projects page shortly after entering IDE

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#277]
**Describe the bug**
Several users have reported that they are getting kicked back to /projects sometimes as quickly as 5 minutes into using the IDE. This issue is caused by the WebSocket connection going down momentarily. We have a fix in the works to mitigate this on the front end, but there need to be some larger fixes on the back end to completely fix the problem.

**To Reproduce**
1. Open a project in the IDE
2. Use the IDE for (random amount of time)
3. See error message when taken back to the /projects page.

**Expected behavior**
A stable IDE

**Additional context**
zendesk `1646`

**Comment by Multishifties** [comment]
`/projects ` no longer exists.

@nol166 please close
