### ISSUE TITLE
Extension marketplace not loading

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#281]
**Describe the bug**
The extension store fails to load in the IDE.

`.45/bin/bootstrap-fork.js --shared` is running however the marketplace loads indefinitely.

**To Reproduce**
1. Open the IDE
2. Click on the extensions button
3. See behavior of the load

**Expected behavior**
Extensions load

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**
Multiple users on zendesk have reported this issue. I was able to replicate myself

**Comment by nol166** [comment]
This appears to be resolved

**Comment by nol166** [comment]
Reported again as of an hour ago. Zendesk `1707`.

**Comment by deansheather** [comment]
Zendesk `Ticket #2100`.
