### ISSUE TITLE
Container listed as 0.00/0.00GB after resetting container

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#282]
**Describe the bug**
A user has reported that the container is shown as 0.00GB after resetting. This should be fixed.

**Expected behavior**
The container shouldn't display as having zero capacity

**Desktop (please complete the following information):**
Browser: Google Chrome or Chromium 
Operating System: windows

**Additional context**
zendesk `1690`

**Comment by Multishifties** [comment]
No longer relevant.

@nol166 please close
