### ISSUE TITLE
Files getting reformatted when saving

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#283]
**Describe the bug**
Multiple users have reported that their files are getting reformatted or jumbled when they save.

**To Reproduce**
Investigating

**Expected behavior**
Files are saved without messing with the way they are formatted

**Desktop (please complete the following information):**
Browser: Google Chrome or Chromium 
Operating System: windows 

**Additional context**
Zendesk `1700`

**Comment by nol166** [comment]
I believe this may be related to the auto-save feature in VSCode

**Comment by deansheather** [comment]
A user in Discord experienced jumbled files without auto-save being enabled.

**Comment by deansheather** [comment]
`#1906`
