### ISSUE TITLE
Store: typo in free plan

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#292]
**Describe the bug**
In the store, the free plan says it gives 5 hours of free Fast Time but we only give 1 hour.

**To Reproduce**
1. Open the store
2. Look at the free plan

**Expected behavior**
No typo.

**Comment by Multishifties** [comment]
Issue was resolved with https://github.com/codercom/frontend/pull/173/commits/9b52181a10bc28070902fdeeb18c8d81f37abe99

Is fixed on develop. We just need to push to prod.

**Comment by Multishifties** [comment]
Store page no longer exists

**Comment by Multishifties** [comment]
@nol166 please close
