### ISSUE TITLE
Pressing space for project name prevents further input (Safari)

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#295]
**Describe the bug**
A user has reported that when creating a new project while using Safari, any time you press the space bar in the project name it will no longer accept further inputs. The project only gets made if you click outside the inline text field

**To Reproduce**
1. Open Safari
2. Create a new project
3. Enter a name for the project that includes a space
4. Notice that after pressing space no more characters can be entered

**Expected behavior**
spaces are accepted

**Screenshots**
![screen shot 2019-01-02 at 1 33 28 pm](https://user-images.githubusercontent.com/5651438/50608858-7eb0ad00-0e93-11e9-8cda-9d155ea99755.png)

**Desktop (please complete the following information):**
 - OS: MacOS - Safari

**Additional context**
Zendesk `1801`

**Comment by Multishifties** [comment]
Projects page no longer exists.

@nol166 please close
