### ISSUE TITLE
Site crashes when pasting in long lines

### ISSUE THREAD

**Issue by ReconCubed** [codercom/bugs#30]
When pasting in a rather long (single) line into a document, the entire web app freezes and crashes. Causing you to manually restart

1. Create an empty CSS file
2. Paste a long .min.css line into the file

**Expected behaviour**
For the app to paste the content and NOT crash.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67.0.3396.99

**Comment by nol166** [comment]
@ReconCubed Hey thanks for sharing this issue. I will make sure it is addressed.

**Comment by jaymeramsay** [comment]
This appears to be fixed.
