### ISSUE TITLE
Docs: mobile navigation menu doesn't contain "Cdr" link

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#302]
**Describe the bug**
"Cdr" isn't listed in the navigation menu on our docs page for mobile devices/smaller viewports.

**To Reproduce**
1. Go to https://coder.com/docs on a mobile device or simulated smaller viewport
2. Click on the navigation selection box
3. Notice that "Cdr" isn't displayed
4. Open the page on a desktop browser
5. Notice that "Cdr" is displayed in the navigation sidebar

**Expected behavior**
Cdr should be displayed in the list as it is on desktop browsers.

**Screenshots**
Mobile:
![mobile](https://awau.moe/c58ab2.png)

Desktop:
![desktop](https://awau.moe/ef00de.png)

**Additional context**
Reported via Discord.

**Comment by deansheather** [comment]
@Multishifties

**Comment by Multishifties** [comment]
Patch has been developed and is fixed on our local development servers. Should be fixed with next roll out to Production.

**Comment by Multishifties** [comment]
Has since been patched. (but we've also removed this page)

@nol166 please close
