### ISSUE TITLE
"Connection to server closed" popup every time i navigate from ide back to project page.

### ISSUE THREAD

**Issue by pokemonlover1234** [codercom/bugs#312]
**Describe the bug**
Whenever you navigate from the IDE (any project) back to the project selection page (any method), the connection to your server closed notification appears. While I know this is intended, I don't think it should appear if you intentionally leave the page, especially if you use the back button that the IDE itself provides.

**To Reproduce**
1. Go to Projects
2. Open any project
3. Navigate back to the projects page using any method (even manually entering the url has the same result)
4. Notification appears

**Expected behavior**
Notification appears if there was truly an error, or notification is redesigned so it doesn't look like an error when it isn't necessarily one (The red color and exclamation point icon make it look like something went wrong).

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04 (Active Development Version, Disco)
 - Browser Firefox
 - Version 64.0.2 (64-bit)

**Comment by Multishifties** [comment]
Projects page no longer exists.

@nol166 please close
