### ISSUE TITLE
Having collaborator cursor in the same position causes duplicate auto-closing tags

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#313]
Jan 22, 2019 at 1:37:34 PM
**Describe the bug**
A user reported that if their cursor and the cursor of their collaborator were in the same position, auto closing HTML tags were duplicated twice. This might be because emmet isn't aware that they are two individual cursors because they are in the same position.

**Environment**
Production

**To Reproduce**
1. Open the IDE
2. Invite someone to collaborate
3. Create an HTML file
4. Place your cursor in the same position as the collaborator
5. Start typing `<div>`
6. Notice that the self-closing tag is placed twice.

**Expected behavior**
Self-closing tags are only initiated once per user

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 70

**zendesk**
`1918`

**Comment by Multishifties** [comment]
Collaboration has been removed.

@nol166 please close
