### ISSUE TITLE
Dashboard: can't save display name in settings

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#325]
**Describe the bug**
There's no way of saving your display name in the settings window that I can see. There's no submit button, and clicking return does nothing.

**To Reproduce**
1. Go to Settings
2. Change your display name (keep #242 in mind)
3. Try to save it by clicking enter
4. Refresh
5. Notice that it's not saved

**Expected behavior**
There should be a way to save the display name.

**Screenshots**
n/a

**Desktop:**
* OS: Linux
* Browser: Chromium Version 71.0.3578.98

**Additional context**
Reported via Zendesk `Ticket #2006`.

**Comment by nol166** [comment]
I wasn't able to replicate this on prod. Were there spaces in the display name? @deansheather

**Comment by Multishifties** [comment]
settings is now removed.

@nol166 please close
