### ISSUE TITLE
updates to VSCode

### ISSUE THREAD

**Issue by rholland** [codercom/bugs#331]
This is not a bug but a request for information.  I would like to use the most recent Python plugins (from this month - February) from MS but the current version of VSCode only accepts the Python plugins from last October.  When do you expect to update Coder to accept the most recent Python plugins? Many thanks for the very nice browser interface for VSCode!

**Comment by foresthoffman** [comment]
Hello @rholland, the tentative plan is to update the extensions in the next week or so. 👍 

Cheers,
Forest
