### ISSUE TITLE
workbench.view.collaboration resource is not available

### ISSUE THREAD

**Issue by temco** [codercom/bugs#334]
**Describe the bug**
when I clicked the welcome page of either project, and chose *Keep Coding* -> *Collaborate*, an error at the bottom-right corner said: *Unable to open 'workbench.view.collaboration': resource is not available*. And I didn't know how can I go on to collaborate.

**To Reproduce**
1. Go to 'coder.com/projects'
2. Click on 'Open in VSCode' of either project
3. Click 'Keep Coding' -> 'Collaborate' on the 'Welcome' Page

**Expected behavior**
I just wanted to invite someone and tested the collaboration mode.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.3
 - Browser Chrome 72.0.3626.119

**Comment by foresthoffman** [comment]
Hello @temco,

This is expected behavior as collaboration is currently disabled. The collaboration feature was causing some issues elsewhere and was disabled in favor of stability. Therefore I'll be closing this issue.

Thanks,
Forest

**Comment by baryla** [comment]
@foresthoffman, when will the feature be re-enabled? Or a better question - have you guys figured out a fix for the other issues that caused the collaboration feature to be disabled? We really need this feature.

**Comment by foresthoffman** [comment]
Hi @baryla,

Collaboration is definitely a cool feature, and it will eventually return. We want to provide features that are solid and dependable, and we don't want to sacrifice stability to do so. So, we'll revisit the collaboration feature in the future.

Thanks,
Forest
