### ISSUE TITLE
 MS Python extension does not show up in extension list

### ISSUE THREAD

**Issue by rholland** [codercom/bugs#337]
MS Python extension does not show up in the extension list and the vsix install option in the dropdown menu is inoperable.  Any idea on when the MS Python extension will be available for Coder?  

Is there an alternative way to install a vsix file in Coder?  

Thanks.

**Comment by foresthoffman** [comment]
Hi @rholland,

This is a known issue, and we're currently working on it. It's due to a vscode version constraint on the Python extension.

Thanks for letting us know,
Forest

**Comment by nol166** [comment]
Similar issue also impacts VSCodeVIM

**Comment by nol166** [comment]
And ESLint

**Comment by memelaser** [comment]
Another bug #340 is related to this, this is happening because the packages are ghost packages. Go to the bug page for more

**Comment by foresthoffman** [comment]
Closing in favor of https://github.com/codercom/bugs/issues/340
