### ISSUE TITLE
IDE: Syntax highlighting for compiler macros in Rust doesn't work

### ISSUE THREAD

**Issue by gerd2002** [codercom/bugs#34]
**Describe the bug**
Compiler macros in rust (e.g. `#[derive(Debug)]`) are displayed as normal text, instead of being highlighted (my usual color scheme uses a slightly darker gray than the usual text color for this),

**To Reproduce**
1. Open a rust file.
2. Type `#[derive(Debug)]`

**Expected behavior**
The compiler macro gets highlighted

**Screenshots**
![error](https://writing-bots.in-ya.ml/i/h3sk.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 62.0b1

**Comment by nol166** [comment]
@gerd2002 Thank you for reporting this one. We are on it.

**Comment by jaymeramsay** [comment]
This is still a valid issue. I see no syntax highlighting for Rust in MacOS Chrome or FF.

**Comment by jaymeramsay** [comment]
This is behaving as intended.

**Comment by gerd2002** [comment]
@jaymeramsay May I ask how missing highlights for a widely used syntax is intended?

**Comment by ammario** [comment]
@gerd2002 Sorry for the mix-up, this is intended behavior of the current syntax highlighter but we should definitely improve. I have moved this issue into our internal feature tracker

**Comment by gerd2002** [comment]
Thank you for clarifying!
