### ISSUE TITLE
Extensions: can't install extensions due to missing vspackages

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#340]
**Describe the bug**
When you attempt to install `vscodevim.vim` or any other affected package from the extensions menu, you receive an error with a button that lets you download the extension manually which takes you to https://extensions-api-dot-coder-production.appspot.com/publishers/vscodevim/vsextensions/vim/1.1.0/vspackage.

This link is a 404, which means the extensions API is returning search results for `vscodevim.vim` when the package is not actually available.

**Known affected packages**
- `tht13.python`
- `vscodevim.vim`

**To Reproduce**
1. Open the IDE
2. Search for `vim` in the extensions menu
3. Install `vscodevim.vim`
4. Notice that it failed and there's a notification
5. Click the button in the notification
6. Notice 404

**Expected behavior**
`vscodevim.vim` and other packages should install correctly.

**Screenshots**
n/a

**Additional context**
Reported via Zendesk `#2152`.

**Comment by ben4523** [comment]
Hi samething for Tslint : 

>  Failed to install 'dbaeumer.vscode-eslint'.

Thanks

**Comment by memelaser** [comment]
`ms-python.python
dbaeumer.vscode-eslint
eamodio.gitlens
editorconfig.editorconfig
redhat.vscode-yaml`
some other ones

**Comment by foresthoffman** [comment]
vscodevim failed to register commands:

```
webpack-internal:///./lib/vscode/src/vs/workbench/browser/parts/notifications/notificationsAlerts.ts:36 Error: command 'toggleVim' not found
    at Proxy.CommandService._tryExecuteCommand (webpack-internal:///./lib/vscode/src/vs/workbench/services/commands/common/commandService.ts:57)
    at eval (webpack-internal:///./lib/vscode/src/vs/workbench/services/commands/common/commandService.ts:51)
```
```
vscodevim.vim failed:  Invalid regular expression: /([^\s~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?](?:(?:(?<=[A-Z_])[A-Z](?=[\sA-Z0-9~!@#$%^&*()-=+[{]}\|;:'",.<>/?]))+|(?:(?<=[0-9])[0-9](?=[\sA-Z0-9~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]))+|(?:(?<=[_])[_](?=[\s~!@#$%^&*()-=+[{]}\|;:'",.<>/?]))+|[^\sA-Z0-9`~!@#$%^&*()-=+[{]}\|;:'",.<>/?]))|[`~!@#$%^&\()-=+[{]}\|;:'",.<>/?]+|$^/: Invalid group (at eval (eval at exports.requireModule (/Users/andrei/Downloads/code-server-1.31.0-20-x86_64-apple-darwin/code-server:468:27372), <anonymous>:231290:25))
```

**Comment by memelaser** [comment]
Hold on, I'm a little confused, how does that apply to the packages missing? Something failed so the packages don't show up?

**Comment by andreimc** [comment]
@memelaser Hi @andreimc, Yes, code-server uses ours. The marketplace behind coder.com itself is not open source. The official marketplace doesn't appear to be curated, so having our own helps weed out extensions that will bloat the system, or are deprecated, etc.

The marketplace for coder.com was reloaded just a little bit ago, so if you're able to download an extension it should install properly now. There still appears to be some hiccups with websockets, so searching the marketplace may be hindered.

When that's sorted, the most helpful thing will be to make bug reports with a decent amount of detail regarding any dis-functional extensions, and requests for extensions that aren't already on the platform. I'll do my best to accommodate those requests.
Bugs: https://github.com/codercom/bugs/issues
Feature Requests: https://github.com/codercom/features/issues

**Comment by andreimc** [comment]
they refreshed the packages recently

**Comment by foresthoffman** [comment]
The packages exist, but yes something along the line is causing a failure.

**Comment by foresthoffman** [comment]
There are a lot of extension reports coming in so i'm trying to condense them a bit. They're all adjacent issues. :)

**Comment by memelaser** [comment]
Ok, thanks for the explanation! I was really confused...

**Comment by andreimc** [comment]
the vim issue is related to: https://github.com/VSCodeVim/Vim/issues/3522

**Comment by foresthoffman** [comment]
@andreimc nice find!

**Comment by memelaser** [comment]
I can install ms-python.python. Not sure what happened, but whatever happened fixed that.

**Comment by foresthoffman** [comment]
ms-python.python and dbaeumer.vscode-eslint should be good now.

**Comment by worldworm** [comment]
https://github.com/codercom/code-server/issues/30
https://github.com/codercom/bugs/issues/341
@andreimc 
> The marketplace behind coder.com itself is not open source.

Hi @foresthoffman Is there a plan to publish the plugin-api as open source?

**Comment by foresthoffman** [comment]
Hi @worldworm,

No, there is no current plan to publish our internal extension API.

Thanks,
Forest

**Comment by foresthoffman** [comment]
Settings sync (`shan.code-settings-sync `) should be good in the next hour or so. Vim and the other extensions mentioned here should be good to go as well.

**Comment by maxjerin** [comment]
Neither of those extension work for me. I've been trying to get them to work so I can use coder.com on iPad Pro. I previously opened [Bug#250](https://github.com/codercom/bugs/issues/250), but since that is more of UIKit issue, I was hoping I could use Vimacs and use the `h, j, k, l` to move around.

![image](https://user-images.githubusercontent.com/2186846/54868500-65691f80-4d63-11e9-858f-284d290d28f7.png)

Extension installed, but nothing appears in settings
![image](https://user-images.githubusercontent.com/2186846/54868518-a3664380-4d63-11e9-903b-2a8547f778cd.png)
