### ISSUE TITLE
Extensions missing - why is the url: https://v1.extapi.coder.com

### ISSUE THREAD

**Issue by andreimc** [codercom/bugs#341]
**Describe the bug**

A lot of extensions missing from: https://v1.extapi.coder.com

**To Reproduce**
Search for some extensions, any that don't have an image will error out

**Expected behavior**
Should be able to install extensions

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSx
 - Browser Chrome
 - Version 70

**Additional context**
Why is the extension url set to this https://v1.extapi.coder.com?

**Comment by foresthoffman** [comment]
Hi @andreimc,

Thanks for reporting this. This is a known issue and we're working on it.

On coder.com we pull extensions from a curated internal list, which is why that URL exists.

Cheers,
Forest

**Comment by foresthoffman** [comment]
Closing in favor of https://github.com/codercom/bugs/issues/340
