### ISSUE TITLE
IDE fails to load

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#343]
Mar 5, 2019 at 4:09:55 PM
**Describe the bug**
Users are reporting that when signing in with GH they are getting redirected to ide.coder.com, but the page is unresponsive.

**Environment**
Production

**To Reproduce**
1. Log in with github
2. See 502 error after ide.coder.com fails to load 

**Expected behavior**
IDE loads

**Screenshots**
![screen shot 2019-03-04 at 12 48 58 pm](https://user-images.githubusercontent.com/5651438/53841015-43009500-3f61-11e9-8669-eb4231860f64.png)

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 70

**Reason for priority**
Major issue

**Comment by arcdigital** [comment]
This is happening for me as well, but I used Google to signup.

**Comment by SHoar** [comment]
this also happened for me.  So far, I've noticed that if I try going back to the login page and loading, or going to the github login page again and retrying, it will load up vscode ... but the transition from black screen to vscode is a bit hesitant.  but, then it works... mind you after several reload/retries, hit or miss at the moment.

**Comment by sr229** [comment]
Have you guys tried https://ide.coder.com?

**Comment by ammario** [comment]
Should be fixed
