### ISSUE TITLE
Reset Container

### ISSUE THREAD

**Issue by tvarwig** [codercom/bugs#348]
In the newest ide.coder.com version is there a way to reset the container as before back to factory state. Before there was a reset button.

**Comment by Omeryl** [comment]
Help -> Reset Container I believe.

**Comment by tvarwig** [comment]
There is a restart container but not reset. Restart does not reset back to factory state.

**Comment by Omeryl** [comment]
@tvarwig Oops, indeed. My brain was playing tricks on me, sorry!

**Comment by wbvtler** [comment]
I am also looking to do a reset. Please help!

**Comment by Multishifties** [comment]
Option to reset container now exists in the IDE under the help menu.

@nol166 please close.
