### ISSUE TITLE
Project Dashboard: Disk Displaying as Full (It's Not)

### ISSUE THREAD

**Issue by jaentwistle** [codercom/bugs#35]
Via Zendesk

"Initially, the default container shows that the disk is full under disk info, even though it isn't. however, after using the container for a bit it works fine"

**Comment by nol166** [comment]
This issue has been fixed.

**Comment by ahmedfarag36** [comment]
in control panel > overview tab under disk storage section it shows me 100% usage, remaining 0 GB however I have only 1 empty project.
THANKS in advance and good work

**Comment by Multishifties** [comment]
No longer relevant as this control panel page no longer exists.

@nol166 please close
