### ISSUE TITLE
vim extension broken - "invalid regular expression" 

### ISSUE THREAD

**Issue by moonlitknight** [codercom/bugs#350]
**Describe the bug**
After installing vscodevim 1.1.0, every keystroke causes
```
TaskQueue: Error running task. Invalid regular expression: /([^\s`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?](?:(?:(?<=[A-Z_])[A-Z](?=[\sA-Z0-9`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]))+|(?:(?<=[0-9_])[0-9](?=[\sA-Z0-9`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]))+|(?:(?<=[_])[_](?=[\s`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]))+|[^\sA-Z0-9`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]*))|[`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?]+|$^/: Invalid group.
```
**To Reproduce**
1. Install vscode.vim extension
2. Open a new file
2. Type pretty much anything 
3. See error

**Comment by foresthoffman** [comment]
Hello @moonlitknight, we're currently tracking this issue here: https://github.com/codercom/code-server/issues/61#issuecomment-470456156. I'll be closing this as a duplicate.

Thank you,
Forest
