### ISSUE TITLE
Java - Unable to run graphical programs

### ISSUE THREAD

**Issue by esQmo** [codercom/bugs#37]
I build a simple game which has 8 files.  I'ù able to javac *.java (creates all class files). But java Main doesn't work. It seems not finding the Main class.

![image](https://user-images.githubusercontent.com/10319812/43134250-5ac0bc84-8f39-11e8-81bc-c13ff7df4832.png)

A simple Hello World program runs, or any program which has one file can be run.

I don't know if it is really a bug or I a doing things wrong.

Files structure:

![image](https://user-images.githubusercontent.com/10319812/43134518-3a184e74-8f3a-11e8-93f1-659f21a46e67.png)

Main class:

![image](https://user-images.githubusercontent.com/10319812/43221889-38d45ffa-9046-11e8-9ef1-b83945fb0bbb.png)

**Comment by nol166** [comment]
@esQmo Hey esQmo! Just to be sure would you mind pasting the body of your `MvcPha.java` file in a comment? Assuming its not too large.

**Comment by esQmo** [comment]
Done, @nol166

**Comment by esQmo** [comment]
I think, and also as duscussed on Discord, this is a limitation of Coder, it is not (yet) capable of running garphical programs.

![image](https://user-images.githubusercontent.com/10319812/43233317-36ff2120-906d-11e8-9884-ed7d447f0e78.png)

**Comment by nol166** [comment]
Thanks for posting that @esQmo. Me and Lyle looked into this today and you are right. We have some limitations when it comes to full blown java rendering right. Sorry for the delayed response.

**Comment by jaymeramsay** [comment]
Any plans to support graphical programs aren't in the near future. We're not sure when we'll able to implement this.
