### ISSUE TITLE
Registration Password

### ISSUE THREAD

**Issue by Proximyst** [codercom/bugs#38]
**Describe the bug**
When registering with a password with extended ASCII characters, it fails and says the input is invalid (without pointing me to the password field; it just says `The input is invalid.`).

**To Reproduce**
1. Go to the signup page.
2. Enter a password such as my attempted one: `g|ÿ_Ö©×yÂ!gùNÕg¯.5ðE{5$ò4-£zö{ß|^RÙøÜ`gÛ¾D»âUäG§PíÙÃÔ¼À|mÛh±®91âbþé´E`
3. Register.
4. Get a vague error.

**Expected behavior**
Registry to go through even though the characters are weird.

**Screenshots**
![https://uwu.whats-th.is/dc7df5.png](https://uwu.whats-th.is/dc7df5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Version: 62.0b10-aurora

**Additional context**

**Comment by nol166** [comment]
```{"error":{"msg":"The provided value is invalid.","validation_errors":{"password":"g|ÿ_Ö©×yÂ!gùNÕg¯.5ðE{5$ò4-£zö{ß|^RÙøÜgÛ¾D»âUäG§PíÙÃÔ¼À|mÛh±®91âbþé´E` does not validate as password"}},"raw_error":"password: g|ÿ_Ö©×yÂ!gùNÕg¯.5ðE{5$ò4-£zö{ß|^RÙøÜgÛ¾D»âUäG§PíÙÃÔ¼À|mÛh±®91âbþé´E` does not validate as password","request_id":"5b57a2ea-622b0e0d5987257d517dfaf9","stack":"goroutine 329458 [running]:\nruntime/debug.Stack(0x11e79c0, 0xc42000ec60, 0x11e8f60)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngo.coder.com/wapi/vendor/go.coder.com/ginmw.Error(0xc420afc000, 0x11e7900, 0xc4219748d0)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/go.coder.com/ginmw/errors.go:41 +0x26\ngo.coder.com/wapi/internal/api.(*Accounts).new(0xc4201380c0, 0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/internal/api/accounts.go:327 +0x11e5\ngo.coder.com/wapi/internal/api.(*Accounts).(go.coder.com/wapi/internal/api.new)-fm(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/internal/api/accounts.go:104 +0x34\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngo.coder.com/wapi/vendor/go.coder.com/ginmw.NoAuth(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/go.coder.com/ginmw/authenticate.go:148 +0x4b\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngo.coder.com/wapi/vendor/go.coder.com/ginmw.Errors.func1(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/go.coder.com/ginmw/errors.go:101 +0x82\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngo.coder.com/wapi/vendor/go.coder.com/ginmw.Logger.func1(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/go.coder.com/ginmw/logger.go:32 +0x7a\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngo.coder.com/wapi/vendor/go.coder.com/ginmw.MaxBodySize.func1(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/go.coder.com/ginmw/bodylimiter.go:45 +0x76\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngo.coder.com/wapi/vendor/go.coder.com/gintrace.Middleware.func1(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/go.coder.com/gintrace/tracer.go:29 +0x171\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngo.coder.com/wapi/vendor/go.coder.com/ipwhitelist.GinHandler.func1(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/go.coder.com/ipwhitelist/whitelist.go:208 +0x212\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/context.go:104 +0x43\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420541440, 0xc420afc000)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/gin.go:332 +0x585\ngo.coder.com/wapi/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420541440, 0x11f3120, 0xc420283c00, 0xc42053bd00)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/github.com/gin-gonic/gin/gin.go:296 +0x153\ngo.coder.com/wapi/vendor/go.coder.com/chttp.NewServer.func1(0x11f3120, 0xc420283c00, 0xc42053bd00)\n\t/home/jenkins/workspace/ackend_develop_wapi_develop-WQCSSTI4IOCJ3KEDTK2ER6HTM5RYV2CVYIM5WX3OYCTVSI34ADNQ/go/src/go.coder.com/wapi/vendor/go.coder.com/chttp/server.go:59 +0x9d\nnet/http.HandlerFunc.ServeHTTP(0xc4206cd080, 0x11f3120, 0xc420283c00, 0xc42053bd00)\n\t/usr/local/go/src/net/http/server.go:1947 +0x44\nnet/http.serverHandler.ServeHTTP(0xc4201d4410, 0x11f3120, 0xc420283c00, 0xc42053bd00)\n\t/usr/local/go/src/net/http/server.go:2694 +0xbc\nnet/http.(*conn).serve(0xc42224d220, 0x11f3de0, 0xc421be2c00)\n\t/usr/local/go/src/net/http/server.go:1830 +0x651\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2795 +0x27b\n"}```

**Comment by ThyLeader** [comment]
@Proximyst our passwords currently require UTF-8 and have a max length of 70 bytes

**Comment by jaymeramsay** [comment]
This appears to be fixed now.
