### ISSUE TITLE
Terminal is freezing

### ISSUE THREAD

**Issue by maishsk** [codercom/bugs#40]
**Describe the bug**
When trying to open a terminal it just hangs

**To Reproduce**
1. Go to 'IDE'
2. Click on 'Terminal'
3. See Terminal stall

**Expected behavior**
Should open terminal 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 67.0.3396.99

**Comment by foresthoffman** [comment]
@maishsk Are you able to view your Containers Page via the Dashboard? There should be a disk usage display. Could you please report what it reads?

For example, mine looks like this:
![screen shot 2018-07-25 at 12 55 51 pm](https://user-images.githubusercontent.com/2442905/43218467-1add9034-900a-11e8-9690-36a44586cd78.png)

**Comment by maishsk** [comment]
Yes..




___________________
Maish Saidel-Keesing
My Blog <http://technodrone.blogspot.com> - @maishsk
<http://twitter.com/maishsk>

**Comment by foresthoffman** [comment]
Are you still experiencing this behavior? Please be sure to refresh your browser.

**Comment by foresthoffman** [comment]
We've made some recent fixes that should have taken care of this. Be sure to refresh your browser, and let us know if you experience this behavior again. Thanks!
