### ISSUE TITLE
High load in container

### ISSUE THREAD

**Issue by maishsk** [codercom/bugs#41]
**Describe the bug**
Container is not responding properly

![image](https://user-images.githubusercontent.com/1918139/43143194-dd5abd2e-8f62-11e8-9f1a-1de492104597.png)

**Comment by foresthoffman** [comment]
Hello @maishsk,

In order to best determine the issue and address it accordingly, could you please provide more context to the issue? Information such as what commands you were running previously, or what files you were trying to modify would be helpful.

Best,
Forest

**Comment by maishsk** [comment]
I tried to run a simple

rm -rf <folder>
git pull
git fetch
git push

___________________
Maish Saidel-Keesing
My Blog <http://technodrone.blogspot.com> - @maishsk
<http://twitter.com/maishsk>

**Comment by foresthoffman** [comment]
We've made some recent fixes that should have taken care of this. Be sure to refresh your browser, and let us know if you experience this behavior again. Thanks!
