### ISSUE TITLE
Website: X on 'Don't worry screen'

### ISSUE THREAD

**Issue by nhuebecker** [codercom/bugs#42]
**Describe the bug**
When entering a valid asses key, if there are not enough 'slots', a you can not assess the site at this time warning window appears. The X on this window is non-functional.

**To Reproduce**
1. Go to coder.com
2. Click on signup
3. Enter a Alpha Key
4. Try to exit Warning Screen

**Expected behavior**
It should exit!

**Screenshot**
![image](https://user-images.githubusercontent.com/15057364/43148130-ab4a41ae-8f32-11e8-9c72-081a62ade296.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 67.03

**Comment by kylecarbs** [comment]
This screen has been removed.
