### ISSUE TITLE
Project data not removed when the project is deleted.

### ISSUE THREAD

**Issue by DylanKeir** [codercom/bugs#44]
**Describe the bug**
Data is not removed when a project is deleted.

**To Reproduce**
1. Create a project.
2. Create a file in the project.
3. Delete the project.
4. Create a new project with the exact same name and the files will still be there.

**Expected behavior**
A new project would be created without old data as it is supposed to delete when the project is deleted.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 67.0.3396.99 (Official Build) (64-bit)

**Comment by JuanPablo2655** [comment]
this error broke my entire project

**Comment by JuanPablo2655** [comment]
this error broke my project

**Comment by ammario** [comment]
Fixed :)
