### ISSUE TITLE
IDE: Indentation halved with non-default settings

### ISSUE THREAD

**Issue by foresthoffman** [codercom/bugs#45]
**Describe the bug**
Indentation is being broken in half. Graphically, the tab/space indicators are displayed, but the actual tab/space characters only fill up half the whitespace that they should.

With no user indentation settings provided, refreshing appears to fix the issue.

**To Reproduce**
1. Launch a project.
2. Open the settings page. File > Settings.
3. Search for `"tab"`.
4. Set the `"editor.tabSize"` setting to some non-default number, e.g. `2`.
5. Save the settings.
6. Use tabs in a file.

**Expected behavior**
Tabs should have been full-width, not halved. And the tab-symbols should not overlap the rest of the text.

**Screenshots**
https://vgy.me/ohH1hm.gif
https://vgy.me/aq1nmM.gif

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 67.0

**Comment by foresthoffman** [comment]
Was also reported via zendesk.

**Comment by haydennyyy** [comment]
You could do something like this in load-time code...
```js
var settings = require(/* Location of the user's settings.json file */);

if(settings != {} || settings != null || settings != undefined) {
  /* Variable that settings changes */.tabSize = settings.editor.tabSize * 2
}
```

I've never done much with the VSC code but I'm sure that's doable... I can try and find where to put the insertion if needed

**Comment by deansheather** [comment]
Zendesk `Ticket #398`.

**Comment by deansheather** [comment]
Discord user reproduced the bug:
![screenshot](https://cdn.discordapp.com/attachments/467359968421740574/477758607321202689/unknown.png)
![screenshot](https://cdn.discordapp.com/attachments/467359968421740574/477758659720511518/unknown.png)

**Comment by jaymeramsay** [comment]
this is still a valid issue.
