### ISSUE TITLE
IDE: Loading: Refresh button is always accessible

### ISSUE THREAD

**Issue by lobsterhands** [codercom/bugs#46]
**Describe the bug**
The Bobo 'Refresh' button is accessible prior to its necessity.

**To Reproduce**
1. Go to your Dashboard Projects and click "Open in IDE" (or refresh your IDE page)
2. Explore with your mouse in the center of the page just below the bottom of the IDE loading info
3. When your cursor changes to `pointer` style, click
4. The page should reload and begin loading the IDE again

**Expected behavior**
Not having a hidden button which restarts my IDE load attempt

**Screenshots**
![refresh-bobo](https://user-images.githubusercontent.com/1688881/43166254-ae57138a-8f5b-11e8-8c99-37789ce257b0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linus
 - Browser: 
 - Version: Version 64.0.3282.119 (Official Build) (64-bit)

**Comment by jaymeramsay** [comment]
this issue has been addressed.
