### ISSUE TITLE
Bug/Feature: need "resend verification code" that allows users to enter different phone number

### ISSUE THREAD

**Issue by jhalek90** [codercom/bugs#48]
**Describe the bug**
user enters the wrong phone number, mistypes a digit, cant resend verification.

**To Reproduce**
1. Go to signup
2. enter mistyped phone number
3. cant verify
4. cant edit phone number

**Expected behavior**
"resend verification" button, that allows a new number to be entered

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version current production

**Comment by jaymeramsay** [comment]
This has been implemented.
