### ISSUE TITLE
IDE: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#49]
**Describe the bug**
Javascript error is thrown:

```
Cannot read property 'style' of null
/bundle.js:2213
/bundle.js:2213 Array.()
/bundle.js:2213 e.()
/vendors~main.bundle.js:68 w()
/vendors~main.bundle.js:68 Generator._invoke()
/vendor
```

**To Reproduce**
1. Log into the IDE
2. View the error

**Expected behavior**
Javascript error is not thrown.

**Additional context**
Reported via Zendesk.

**Comment by foresthoffman** [comment]
More context is needed regarding how this error appeared, before an internal issue can be created.
