### ISSUE TITLE
IDE: margin between lines in the terminal is too small

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#50]
**Describe the bug**
The margin between lines in the terminal is too small, causing issues with seeing some characters properly (e.g. lowercase i vs. capital I).

**To Reproduce**
1. Open the terminal
2. Fill the terminal with a few lines
3. Notice the margin between lines being too small

**Expected behavior**
A large enough gap between the lines to be able to differentiate characters such as i and I.

**Screenshots**
n/a

**Desktop (please complete the following information):**
OS: Ubuntu 18.04 LTS
Browser: Chrome 67.0.3396.87

**Additional context**
Reported via Zendesk.

**Comment by foresthoffman** [comment]
Can't be reproduced at this time.
