### ISSUE TITLE
IDE: using ctrl+z breaks saving .css files

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#51]
**Describe the bug**
Using ctrl+z in .css files causes the IDE to not save the file correctly when using ctrl+s. Doesn't seem to happen to other files, although testing in other files was limited.

**To Reproduce**
1. Open IDE
2. Edit a .css file
3. Write some styles in the .css file
4. Use ctrl+z to undo a change
5. Save the file
6. Use `cat` from terminal to compare the CSS file displayed by the editor to the actual version saved in the project

**Expected behavior**
The editor saves the files correctly after ctrl+z is used.

**Screenshots**

**Additional context**
Originally reported on Discord.

**Comment by T0TProduction** [comment]
I don't know if this is included in this report, but the .js file that had this for me still, after closing and restarting etc. always corrupts on save. It mixes the old and new version, sometimes having the beginning of a changed line flow into the line that was deleted/changed.

An example of what it looks like:
![image](https://user-images.githubusercontent.com/18548570/43285072-2a1f20f2-911e-11e8-8349-e76c4a8da003.png)

**Comment by foresthoffman** [comment]
@T0TProduction I've noted this, thank you!

**Comment by HorizonShadow** [comment]
I'm sure this is language agnostic, but it's happening for ruby too.


![](https://media.discordapp.net/attachments/467356520711979018/473461781663318026/unknown.png)

**Comment by T0TProduction** [comment]
I also wanted to add that these fusions of old and new version always happen exactly in the same lines, I think this might be related to what I undid with ctr+z at first.

**Comment by kylecarbs** [comment]
Should be fixed.
