### ISSUE TITLE
QA: Google sign in form halts sign-up process

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#54]
**Describe the bug**
User signs up via google. The page pops up and they select their account but the page doesn't move forward after that. User had to sign up via the default form.

**System info**
Browser:  Chrome Version 67.0.3396.99 (Official Build) (64-bit)
OS: Windows 10 Home

**Comment by nol166** [comment]
#2

**Comment by kylecarbs** [comment]
Fixed.
