### ISSUE TITLE
IDE: Top menu bar cluttered with profile picture. Affects ide performance.

### ISSUE THREAD

**Issue by Xenofuscus** [codercom/bugs#55]
**Describe the bug**
The top menu bar is cluttered with profile pictures. See screenshot. The IDE also slows down dramatically.

**To Reproduce**

**Screenshots**
![cluttered_bar](https://user-images.githubusercontent.com/40770300/43212323-453d1950-8ff9-11e8-82a4-69ac2a9d6e6c.png)

**Desktop:**
 - OS: Windows 10 Home Insider Preview
 - Browser qutebrowser 
 - Version 1.3.0

**Comment by ammario** [comment]
cc @kylecarbs

**Comment by Vap0r1ze** [comment]
also on windows 10 pro v1803, google chrome

**Comment by foresthoffman** [comment]
This should be solved now. Thanks!
