### ISSUE TITLE
QA: Terminal font renders incorrectly

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#56]
**Describe the bug**
Font rendering in terminal is wonky.

**Steps to reproduce**
1. open ide
2. open view menu
3. open terminal

![image](https://user-images.githubusercontent.com/5651438/43212493-b4355a16-8ff9-11e8-8ec5-93f4d6834bf2.png)

**zendesk**
256

**Comment by nol166** [comment]
This issue has been fixed.

**Comment by jbrains** [comment]
Yes, now the terminal font looks fantastic. Thank you.
