### ISSUE TITLE
Certain letters not working in terminal

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#57]
**Describe the bug**
Users reporting issues with specific letters in the terminal. Specifically, the letters "t" and "q". The user noted that the letters work in the code editor and sidebar. Additionally, the letters work in the terminal if they are uppercase.

OS: Windows 10 Pro v1803
Browser: Chrome Version 68.0.3440.68 (Official Build) beta (64-bit)

**Zendesk**
268

**Comment by nol166** [comment]
The engineering team has been made aware of the issue. I Will keep everyone updated with the status here.

**Comment by pokemonlover1234** [comment]
I was able to use t yesterday, however it seems to have stopped working again this morning.

**Comment by nol166** [comment]
@pokemonlover1234  Are you using a standard qwerty layout on your keyboard?

**Comment by pokemonlover1234** [comment]
yes I am, with numbad.

On Fri, Jul 27, 2018 at 11:51 AM, John McCambridge <notifications@github.com

**Comment by foresthoffman** [comment]
A fix has been made, this should be solved now.
