### ISSUE TITLE
UI: typo in dashboard for "disk storage remaining"

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#59]
**Describe the bug**
Typo in dashboard when hovering over the disk storage indicator at the top right. "Dist" should be "Disk".

**To Reproduce**
n/a

**Screenshots**
![Screenshot](https://owo.whats-th.is/818572.png)

**Additional context**
Reported via Zendesk.

**Comment by nol166** [comment]
This issue has been fixed.
