### ISSUE TITLE
Docs: opening docs website sometimes gives 526 "SSL certificate not valid" error

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#60]
**Describe the bug**
The documentation website (https://docs.coder.com) sometimes responds with Cloudflare error 526 - SSL certificate not valid.

**To Reproduce**
1. Go to https://docs.coder.com
2. Reload until you get the error

**Expected behavior**
There should be no Cloudflare error.

**Additional context**
Reported via Zendesk.

**Comment by foresthoffman** [comment]
Couldn't reproduce at this time.
