### ISSUE TITLE
Terminal: commands with long output break scroll back

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#62]
**Describe the bug**
Commands that have long output break the scroll back in the terminal. Scrolling up in the terminal will show nothing.

**To Reproduce**
1. Open IDE
2. Open terminal
3. `echo test`
4. `cat /etc/ssh/sshd_config` (long output)
5. Try to scroll up, notice that any terminal output above the top of the terminal window is missing

**Expected behavior**
Should be able to scroll up and view all history.

**Screenshots**
Video: https://awau.moe/c02afb.webm

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium

**Additional context**
Reported via Zendesk.

**Comment by kylecarbs** [comment]
Fixed.

**Comment by deansheather** [comment]
This issue is still occurring.

Zendesk `Ticket #921`.

**Comment by coadler** [comment]
This might be a tmux bug. I ran into this exact issue yesterday when I was using tmux locally
