### ISSUE TITLE
Request for language mounting of older version of python

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#64]
**Describe the bug**
Currently, containers will mount 3.7 but some users need older versions of languages to run their apps correctly.

For any users that wish to use 3.6:
1. run `apt-get remove python3`

2. run:
`sudo apt install build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev`
3. run:
`wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz`

4. run:
`tar xvf Python-3.6.0.tar.xz`

5. run
`cd Python-3.6.0/
./configure
sudo make altinstall`

**Comment by afischer12** [comment]
This also works for 3.6.6. I just replaced all instances of 3.6.0 with 3.6.6 and it installed correctly.

**Comment by jaymeramsay** [comment]
Users can install an old version of python, but they have to uninstall the version that's already there.
