### ISSUE TITLE
QA: IDE: traversing whitespace characters causes cursor to move incorrectly

### ISSUE THREAD

**Issue by foresthoffman** [codercom/bugs#66]
**Describe the bug**
Navigating via the arrow keys within a Python file is causing unusual movement of the cursor. At certain points when traveling left/right, the cursor will travel backward, requiring an extra keypress to move in the desired direction.

This doesn't appear to be limited to Python files, I was able to recreate this behavior in a `.sh` script file.

**To Reproduce**
1. Launch a project.
2. Create a python file (with the `.py` extension).
3. Add a line, prefixed by multiple tabs or spaces.
4. Attempt to move left or right along the line, with the arrow keys.

**Expected behavior**
Keypresses and cursor movement should be consistent and travel in the expected direction.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 67

**Additional context**
Reported via zendesk.

**Comment by pokemonlover1234** [comment]
This seems to be fixed in ONLY python files. js, json, and plain text files still maintain the broken behavior.

**Comment by deansheather** [comment]
Zendesk `Ticket #504`: also happens in .go files, video provided seems to match this report. Waiting for permission to post the video here.

**Comment by nol166** [comment]
This is still an issue

**Comment by ccubed** [comment]
I had this issue just now. If you look, the spacing in the file is also displaying incorrectly. Image provided.

[https://i.imgur.com/nTO6jGx.png](Example Image)

**Comment by Vap0r1ze** [comment]
This also happens for me in js files
![image](https://user-images.githubusercontent.com/20448879/45166527-3cb57a00-b1c5-11e8-8f05-a5300f136b9f.png)
![image](https://user-images.githubusercontent.com/20448879/45166553-50f97700-b1c5-11e8-99e5-d06dda2ba5fc.png)
