### ISSUE TITLE
Saving python file adds ` \ufffd` character resulting in syntax errors

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#68]
**Describe the bug**
When saving a python file that has strings as the argument to a function, it moves the string to a new line. However, this seems to add an invisible \ufffd character, which seems to cause syntax errors. Many more are added if it is edited then saved.

`"\ufffd\ufffd\ufffd\ufffdRaid mode has been activated! All new members wi be e kicd")\ufffd                                 s
elf.bot.raid["mode"].append(str(event.guild.i                                                   self.bot.raid["whitelist"][str(ev
ent.guild.id)] =                                                el                                              event.msg.re
                                                                     ^
SyntaxError: invalid character in identifier`

**Comment by pokemonlover1234** [comment]
I am the original bug reporter. Upon further testing, this behavior is only observed when a string contains Unicode-specific characters, otherwise the expected behavior is maintained.

**Comment by pokemonlover1234** [comment]
I am the original bug reporter. Upon further testing, this behavior is only observed when a string contains Unicode-specific characters, otherwise the expected behavior is maintained.

**Comment by pokemonlover1234** [comment]
It is currently untested whether this invisible character behavior is maintained if the string containing the unicode isn't long enough to warrant being moved. Once i get a chance to test that, I will comment here.

**Comment by nol166** [comment]
@pokemonlover1234 okay thank you. I will keep an eye out.

**Comment by pokemonlover1234** [comment]
Unexpected behavior is maintained, adding invisible �️ characters that only appear upon file reload. These now cause the line `print("")` that used to have `print("⚠️⚠️⚠️")` to be read by the terminal after the three unicode characters are added as `print("__` and after reloading the python the string now looks like `print("��
�
���️�️�️�️�️")` Deleting those then saving only makes them reappear. Before the unicode was deleted,  I was getting errors stating an invalid unicode codepaths such as \xa0s. At this point, the only way I've found to remedy these being recreated after these start appearing is to completely recreate the file. I'm going to try to repro this issue in other file types to see if it isn't limited to python files. @nol166

**Comment by pokemonlover1234** [comment]
I have investigated further, making use of Chrome's Developer tools and taking a look at the console. It seems that in python, whenever certain unicode characters are pasted into a string, this error shows up in the console, which may be related to the invisible character issue
`bundle.js:1107 [1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancing`

The error details:

  | u | @ | bundle.js:1107
  | v | @ | bundle.js:1107
  | e._tokenize | @ | bundle.js:1107
  | e.tokenizeLine2 | @ | bundle.js:1107
  | n.tokenize2 | @ | bundle.js:1107
  | TokenizationSupport2Adapter.tokenize2 | @ | VM4686 standaloneLanguages.js:175
  | ModelLinesTokens._updateTokensUntilLine | @ | VM4184 textModelTokens.js:347
  | ModelLinesTokens._tokenizeOneLine | @ | VM4184 textModelTokens.js:316
  | TextModel._revalidateTokensNow | @ | VM4150 textModel.js:1596
  | (anonymous) | @ | VM4150 textModel.js:1574
  | setTimeout (async) |   |  
  | TextModel._beginBackgroundTokenization | @ | VM4150 textModel.js:1572
  | TextModel._applyEdits | @ | VM4150 textModel.js:1116
  | TextModel.applyEdits | @ | VM4150 textModel.js:1020
  | EditStack.pushEditOperation | @ | VM4168 editStack.js:41
  | TextModel._pushEditOperations | @ | VM4150 textModel.js:1014
  | TextModel.pushEditOperations | @ | VM4150 textModel.js:943
  | CommandExecutor._innerExecuteCommands | @ | VM4242 cursor.js:540
  | CommandExecutor.executeCommands | @ | VM4242 cursor.js:507
  | Cursor._executeEditOperation | @ | VM4242 cursor.js:302
  | Cursor._paste | @ | VM4242 cursor.js:475
  | Cursor.trigger | @ | VM4242 cursor.js:418
  | CommonCodeEditor.trigger | @ | VM4240 commonCodeEditor.js:565
  | EditorHandlerCommand.runCommand | @ | VM4139 coreCommands.js:1475
  | handler | @ | VM4203 editorExtensions.js:81
  | InstantiationService.invokeFunction | @ | instantiationService.js:62
  | StandaloneCommandService.executeCommand | @ | VM4637 simpleServices.js:319
  | paste | @ | VM4224 codeEditorWidget.js:332
  | ViewController.paste | @ | VM4300 viewController.js:25
  | (anonymous) | @ | VM4273 textAreaHandler.js:203
  | Emitter.fire | @ | VM4151 event.js:132
  | (anonymous) | @ | VM4276 textAreaInput.js:256

Also, when testing in Java, the pasting worked without console errors, however when trying to compile, I got ASCII encoding errors. Perhaps the files are created and saved as ASCII but the IDE supports Unicode characters, and so trying to save the file breaks/corrupts them?

**Comment by nol166** [comment]
Hey @pokemonlover1234 I have updated our team with the additional information you provided. Thank you for getting some additional information for us to work with. Much appreciated.

**Comment by pokemonlover1234** [comment]
@nol any updates on this? I'm still experiencing this issue, with it happening reproducibly in JavaScript files. The only way i've found to fix these files are to delete them using rm and creating them again using vim. Recreating the file in the editor does not fix the corruption last time i checked.

**Comment by pokemonlover1234** [comment]
@nol166 oops i pinged wrong nol XD

**Comment by nol166** [comment]
he @pokemonlover1234. We are definitely working on this issue. Seems to be a bit more complicated than we initially thought. I will keep you guys posted

**Comment by pokemonlover1234** [comment]
Thanks for the update!
