### ISSUE TITLE
tmux command not found causes inability to use terminal

### ISSUE THREAD

**Issue by pokemonlover1234** [codercom/bugs#69]
**Describe the bug**
Sometimes the tmux command seems to break or get lost or something (idk). I kept getting tmux: command not found. This continued within every project and after rebooting the container. Only resetting the container worked.

**To Reproduce**
1. Go to any project
2. Open IDE
3. Attempt to open a terminal

**Expected behavior**
tmux works as expected and terminal opens.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [68.0.3440.75 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**
This seems to be an intermittent problem and may not be reproducible. I have a suspicion as to the cause. I'll investigate further later and update the issue if my suspicion is confirmed.

**Comment by nol166** [comment]
Do you happen to remember what you were working on or doing before the issue occurred? Did you install anything or just come back to your project and it was like that?

**Comment by pokemonlover1234** [comment]
I had left a python program running. I came back to seeing the IDE had closed and then tmux stopped working after trying to reboot the project. At the moment I have the same program running and I am waiting for it to time out. If the same issue occurs I'll post here again

**Comment by nol166** [comment]
Okay thank you. I just learned that we had some server issues last night that may have been related. Keep me posted!

**Comment by pokemonlover1234** [comment]
@nol166 I'm not sure if this is related to this or #67, or my specific installation setup, but after the session terminated itself, I am now getting the SSH error and cannot load my projects. The only way I've found to recover from such errors is to reset my container. Until the SSH error is fixed, I won't be installing python 3.6.

**Comment by pokemonlover1234** [comment]
Seems #67 is fixed. Haven't encountered either that error or the tmux error since I left python 3.6.6 uninstalled. Will reinstall that now and keep an eye out for errors.

**Comment by nol166** [comment]
fixed.
