### ISSUE TITLE
IDE: Noticeable slowdown, then unresponsiveness and pegged cpu

### ISSUE THREAD

**Issue by nytopop** [codercom/bugs#7]
Displayed text was also affected, some kind of highlighting all over the place.

![2018-07-23-192424_3440x1440_scrot](https://user-images.githubusercontent.com/7799664/43113218-551bcfca-8eae-11e8-886a-33d39963afcb.png)

Happened while two instances were open and holding down the 'f' key in one. Started to notice a slowdown and shortly after this crash occurred. I can reproduce 100% of the time in `Chrome Version 67.0.3396.99 (Official Build) (64-bit)` and `Firefox dev edition 62.0b10 (64-bit)`.

**Comment by ammario** [comment]
Thanks Eric :+1: cc @kylecarbs

**Comment by jaymeramsay** [comment]
Is your htop running in ssh? Or do you have two browser windows open?

**Comment by jaymeramsay** [comment]
nytopop, has this happened to you again since the last time? We're unable to recreate this issue. What OS are you using? If you can recreate it, could you please send any potential console errors and/or updated screenshots? Thank you so much!

**Comment by nytopop** [comment]
It hasn't happened again during normal use, and seems to be much harder to trigger now, requiring coordinated input from multiple IDE instances. It does still happen though in the case of a lot of keypresses alternating from both sides. It seems to happen most frequently if one IDE instance is not yet fully synced to changes made in the other and you type something on the unsynced side (it's a pretty small window of time).

Reproduction steps that tend to work for me:
- open two windows (w1 / w2)
- on w1, hold down a key for 5-15s
- immediately switch to w2 and hold down a key (at the same cursor position)
- w2 is now frozen (1/6 times or so)
- w1 may or may not freeze depending on additional input in w1 and (rarely happens)

The font issues appear to have been resolved.

What it looks like now (both are unresponsive in this case, w1 on the left and w2 on the right):
![2018-08-16-154651_3440x1440_scrot](https://user-images.githubusercontent.com/7799664/44239083-66eabd80-a16c-11e8-929d-5ab0c105ab9a.png)

Firefox console:
![2018-08-16-154741_3440x1440_scrot](https://user-images.githubusercontent.com/7799664/44239082-66eabd80-a16c-11e8-9c70-5369e12ec344.png)

Chrome console:
![2018-08-16-154759_3440x1440_scrot](https://user-images.githubusercontent.com/7799664/44239081-66eabd80-a16c-11e8-83b4-c31b5d50f69e.png)

Chrome: Version 68.0.3440.106 (Official Build) (64-bit)
Firefox dev edition: 62.0b17 (64-bit)

OS details:
```
[eric@io][~]
λ cat /etc/issue
Debian GNU/Linux buster/sid \n \l

[eric@io][~]
λ uname -a
Linux io 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
```

Something to note: I am on a testing release of debian, that might have something to do with it. I'll try it on windows later to double check, don't have a machine handy right now.

The browser combination doesn't seem to change anything, managed to reproduce on:
- chrome <-> chrome
- chrome <-> firefox
- firefox <-> firefox
