### ISSUE TITLE
IDE: language icons are massive in some areas of the IDE

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#71]
**Describe the bug**
Overly large language icons are being displayed in the language mode selector and the tooltip displayed when hovering over a collaborator.

**To Reproduce**
For language mode selector:
1. Open IDE
2. Open any file
3. Open the language mode selector (click the name of the language in the bottom right)
4. Notice that the displayed language icons are very large

For collaborator active file:
1. Open IDE
2. Invite a collaborator and have them join and open a file
3. Hover over their avatar in the top right
4. Notice that the displayed language icon for the file they are editing is very large

**Expected behavior**
The language icon should be smaller.

**Screenshots**
In collaboration mode (hovering over collaborators name to see their current file):
![screenshot](https://awau.moe/266cad.png)

Language mode selector:
![screenshot](https://cdn.discordapp.com/attachments/467356520711979018/472784272042754058/unknown.png)

**Additional context**
Originally reported via Discord.

**Comment by jaymeramsay** [comment]
thank you, Dean!

**Comment by kylecarbs** [comment]
Fixed.
