### ISSUE TITLE
IDE: saving files doesn't work sometimes

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#72]
**Describe the bug**
Sometimes saving files doesn't work.

**To Reproduce**
Unsure on how to reproduce accurately, although I have noticed this a few times and it has been reported by users.

1. Open IDE
2. Open a file
3. Edit the file
4. Save the file
5. Notice that the unsaved indicator is still on the file
6. `cat` the file from terminal to ensure the changes were saved
7. Notice that the changes were not saved

**Expected behavior**
The file should save properly every time.

**Screenshots**
![screenshot](https://awau.moe/12fa3e.gif)

**Additional context**
Originally reported via Discord.

**Comment by jaymeramsay** [comment]
This is on our radar. We're trying to reproduce the issue so we can find the source of the problem. Thank you!

**Comment by deansheather** [comment]
One user in Discord had this issue when trying to save a very long Python file (700+ lines). The IDE wasn't logging in verbose console that it was sending the [Protocol] filesave event.

**Comment by jaymeramsay** [comment]
zendesk tickets ```550,  755```

**Comment by nol166** [comment]
`1052`

**Comment by deansheather** [comment]
Users in Discord reporting this in Python and .tsx files, claiming that they aren't having issues in other files.

**Comment by jaymeramsay** [comment]
```zendesk 1144```

**Comment by nol166** [comment]
zendesk `1156`

**Comment by nol166** [comment]
`1242`

**Comment by jaymeramsay** [comment]
```1258```

**Comment by jaymeramsay** [comment]
```1269```

**Comment by jaymeramsay** [comment]
```1270```
