### ISSUE TITLE
UI: login form input behind Coder logo on Chrome for Android

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#73]
**Describe the bug**
Form inputs for the login screen appear behind the Coder logo in the header bar and the "incompatible browser" message when the keyboard is open, possibly making it difficult to focus the email field if the keyboard is open.

**To Reproduce**
1. Open Coder.com login page: https://coder.com/login
2. Click on an input field
3. Notice how the email field appears behind the Coder logo

**Expected behavior**
The email field should not be able to show behind the logo or the browser compatibility notice.

**Screenshots**
![screenshot](https://awau.moe/af12c4.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S5 kledtv running Lineage OS 14.1
 - OS: Android 7.1.2
 - Browser: Chrome for Android
 - Version: 67.0.3996.87

**Additional context**
Originally reported via Discord.

**Comment by jaymeramsay** [comment]
Thank you, Dean! We're currently unable to duplicate this issue, but we'll definitely keep an on this because login is essential. We're continuing to improve the mobile experience for our users overall.

**Comment by Multishifties** [comment]
Patched this just now and have a PR pending. Should be fixed with the next patch roll-out.

This bug was my bad. I should have more thoroughly tested that.
