### ISSUE TITLE
IDE: C++ syntax highlighting not working fully

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#74]
**Describe the bug**
C++ syntax highlighting seems to not be fully working.

**To Reproduce**
1. Open the IDE
2. Open or create a [C++ file with content](https://raw.githubusercontent.com/leachim6/hello-world/master/c/c%2B%2B.cpp)
3. Notice that syntax highlighting isn't fully working

**Expected behavior**
Syntax highlighting should work properly and color more things.

**Screenshots**
![screenshot](https://owo.whats-th.is/29499f.png)

**Additional context**
Reported via Discord.

**Comment by jaymeramsay** [comment]
Thank you, Dean!

**Comment by Xenofuscus** [comment]
Issue in [`js/issues/279`](https://gh.coder-internal.com/js/issues/issues/279)

**Comment by kylecarbs** [comment]
Fixed.
