### ISSUE TITLE
IDE: Filename overlaps icon

### ISSUE THREAD

**Issue by adityakr082** [codercom/bugs#75]
**Describe the bug**
First character of the filename overlaps a part of the icon.

**To Reproduce**
1. Open the IDE
2. Create a file
3. Close and re-open Explorer

**Expected behavior**
Filename should be clearly separate from file icon.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/21287366/43401001-be806c72-942c-11e8-8eca-0b3a7c2a73f2.png)

**Comment by jaymeramsay** [comment]
Hey adityakr082, thank you for bringing this to our attention. We'll go ahead and take a look at this and work on a fix :)

**Comment by lobsterhands** [comment]
@adityakr082, could you please provide specs for the OS and browser you are using to expose text/icon overlap issue?

**Comment by adityakr082** [comment]
OS: Windows 10 Single Language
Browser: Firefox Nightly 63.0a1

**Comment by jaymeramsay** [comment]
this has been addressed.

**Comment by nol166** [comment]
This seems to still be an issue on Firefox with a Mac. Opening.
