### ISSUE TITLE
File contents going out of sync with disc. 

### ISSUE THREAD

**Issue by Nepaltechguy2** [codercom/bugs#76]
**Describe the bug**
If you create a file via terminal (via `git pull`, `vim` or even `npm init`), the file gets created, but cannot be edited via the editor.

Or, if you create a file in the editor, it doesn't sync with terminal (so doing `cat test.txt` shows that the file exists, but it has no contents).

**To Reproduce**
1. Go to the terminal
2. Type `vim test.txt`
3. Exit and double click file on left sidebar

or backwards :)

**Expected behavior**
Show the file text.

**Screenshots**
Video: https://youtu.be/eN5YYRxzLkg
Ignore anything related to `DebateSpyder` I forgot to switch out of it in OBS. 

**Desktop (please complete the following information):**
 - OS: works on all
 - Browser: was using Chrome 67 and Firefox 61

**Comment by Nepaltechguy2** [comment]
Third video showing other way around: https://www.youtube.com/watch?v=C5PGEj-OmDg

**Comment by Nepaltechguy2** [comment]
I don't know about other people, but this is working again for me.

**Comment by Nepaltechguy2** [comment]
Reopening because running `git checkout branch2` causes the files to go out of sync again.

**Comment by Nepaltechguy2** [comment]
apparently this issue has been fixed. :+1:

**Comment by ammario** [comment]
Thank you for the comphrensive report and follow ups 😊

**Comment by deansheather** [comment]
Someone in Discord has this issue again:
![screenshot](https://media.discordapp.net/attachments/467359968421740574/478161206264463363/unknown.png)

**Comment by pokemonlover1234** [comment]
Same guy from discord also reports creating the file via IDE and editing via vim also causes the sync issue.

**Comment by pokemonlover1234** [comment]
Also, I'm able to reproduce the issue

**Comment by ammario** [comment]
@pokemonlover1234 please provide reproduction instructions. I'm having trouble.

**Comment by pokemonlover1234** [comment]
1) Create file via IDE
2) Insert some text
3) Save the file
4) Close the file in IDE
5) Open Terminal
6) `vim` the file
7) Add some text in vim and save the file
8) Reopen file in the editor and `cat` the file in terminal
9) Notice edits from `vim` are not present.

**Comment by ammario** [comment]
Thank you @pokemonlover1234 ! Will try to fix this today

**Comment by ammario** [comment]
Reloading the page seems to fix this problem, a mitigation is being deployed, but the full solution is probably another day out.

**Comment by deansheather** [comment]
Someone in Discord reports having a file that shows as saved in the IDE without any contents on disk. They reloaded the IDE and couldn't delete the file from the explorer.

**Comment by nol166** [comment]
zendesk ticket `617`
