### ISSUE TITLE
IDE: "Clide failed to connect, reconnecting" error while opening IDE

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#77]
**Describe the bug**
Some users are reporting "Clide failed to connect, reconnecting" errors (in the IDE connection log displayed on the screen) while trying to open the IDE. These errors spam repeatedly until you exit the IDE (one user waited for 10 minutes).

One user reported the following error from console:
```
WebSocket connection to 'wss://v1.clide.coder.com/?api_key=xxx&workspace_id=123&id=xxx' failed: Error during WebSocket handshake: Unexpected response code: 500
```

**To Reproduce**
1. Open the IDE
2. Notice that it won't connect
3. Notice that the "Clide failed to connect, reconnecting" error is spammed in the connection log displayed on the screen

I've experienced this issue in the past, had to recreate the project to be able to get in. Couldn't reproduce reliably.

**Expected behavior**
The IDE should connect properly.

**Additional context**
Reported via Zendesk `Tickets #316, #322`. Reported via Discord.

**Comment by tilda** [comment]
Can repro

**Comment by deansheather** [comment]
Can't connect to my container right now.

**Comment by deansheather** [comment]
Also reported again on Zendesk `Ticket #324`.

**Comment by Mczty** [comment]
can repro

**Comment by JuanPablo2655** [comment]
can't connect either
reeeeeeeeeee

**Comment by pokemonlover1234** [comment]
can repro

**Comment by jaymeramsay** [comment]
Hey everyone. Thank you for the feedback. The IDE should be up and running now. Can you get back in ok?

**Comment by deansheather** [comment]
Incident: https://status.coder.com/incidents/bpsvbv6b27zc

**Comment by santu9** [comment]
Hi, I am facing this issue, not able to open my project in IDE.
![image](https://user-images.githubusercontent.com/8284626/44339841-e7e9d380-a450-11e8-8a34-da436aa1a933.png)

**Comment by ammario** [comment]
@santu9 what's your Coder username?

**Comment by juanmaa1414** [comment]
Sorry for the re-comment, I've also experimenting the same issue now.

**Comment by ammario** [comment]
@juanmaa1414 please send your Coder username

**Comment by juanmaa1414** [comment]
My Coder username Is juanma.

**Comment by ammario** [comment]
Does restarting your container fix it?

**Comment by juanmaa1414** [comment]
Hmm, but I've installed many utilities with apt. I would rather wait for it to be solved.. I've already tried with Ctrl + F5 and deleting all cookies but no result.

**Comment by ammario** [comment]
Restarting your container won't result in data loss. It's just flipping it from off to on.

**Comment by juanmaa1414** [comment]
Oh.. just a confusion. Yep! I have already tried to restart the container. But no result.

**Comment by ammario** [comment]
@juanmaa1414 could you show me your network tab? I'd like to see what the exact error is. Please be cautious about exposing API keys.

**Comment by juanmaa1414** [comment]
![captura de pantalla de 2018-08-20 18-43-45](https://user-images.githubusercontent.com/8095304/44368487-66725f80-a4a9-11e8-81bc-22267f047d02.png)
Part of the requests. Clide service is giving 500.

**Comment by ammario** [comment]
I imagine this doesn't happen to new workspaces?

**Comment by juanmaa1414** [comment]
Creating new projects and open them, the problem does not happen.

**Comment by santu9** [comment]
My user id is santu9.

**Comment by ammario** [comment]
@santu9 @juanmaa1414 we deployed a fix. Please let us know if this continues happening on old workspaces.

**Comment by juanmaa1414** [comment]
@ammario now is all working for me. Super thumbs up!

**Comment by ammario** [comment]
Glad to hear that. Thanks for going through these Alpha pains with us :)

**Comment by santu9** [comment]
IDE is loading now. Thanks for the quick fix.

**Comment by dvdrom000** [comment]
Getting the errors now, only been using coder for a week, first time seeing these.

**Comment by dvdrom000** [comment]
![image](https://user-images.githubusercontent.com/1829973/44831311-69b8ca00-abd2-11e8-8715-dfdc14016362.png)
