### ISSUE TITLE
UI: SVG icons not showing on Safari

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#79]
**Describe the bug**
SVG icons aren't showing.

**To Reproduce**
1. Open the dashboard
2. Notice that some/most/all SVG icons aren't showing

**Expected behavior**
The SVG icons should be visible.

**Screenshots**
![screenshot](https://cdn.discordapp.com/attachments/467356555583553537/473841966971617280/Screen_Shot_2018-07-31_at_8.15.10_AM.png)
![screenshot](https://cdn.discordapp.com/attachments/467356555583553537/473843896011587594/Screen_Shot_2018-07-31_at_8.21.10_AM.png)
![screenshot](https://cdn.discordapp.com/attachments/467356555583553537/473843729644388352/Screen_Shot_2018-07-31_at_8.25.13_AM.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser: Safari
 - Version: 11.1.2

**Additional context**
Reported via Discord.

**Comment by kylecarbs** [comment]
Fixed.
