### ISSUE TITLE
Dashboard: Containers: Carousel needs to check for out of bounds

### ISSUE THREAD

**Issue by lobsterhands** [codercom/bugs#80]
**Describe the bug**
The containers page carousel allows for navigation outside useful bounds.

**To Reproduce**
1. Go to the [containers](https://coder.com/dashboard/containers) page 
2. Click on the left or right arrow in the carousel (where you see Quick Tips)
3. Note that you can click out of bounds and display nothing
4. If you click 5 times past the end of the list, you have to click 5 times the opposite direction to get useful information back.

**Expected behavior**
I expect to be able to explore available options in the carousel with navigation limited to the end of the list.

**Video (used with reporter's permission)**
http://kb.velma.video/watch/cFiwbmF9Cm

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Chrome
 - Version: Version 64.0.3282.119 (Official Build) (64-bit)

**Comment by jaymeramsay** [comment]
This has been fixed.
