### ISSUE TITLE
/coder/mnt/ folders: When removed from projects by a user, user's folder remains but is empty

### ISSUE THREAD

**Issue by pokemonlover1234** [codercom/bugs#81]
**Describe the bug**
When you are invited to another user's project, a folder is created under /coder/mnt named after the user's username. If (and when) you are removed from all projects from that user, that folder remains and is empty.

**To Reproduce**
1. Get invited to a project by user xxxxxx
2. Use command `dir` or `ls` in \coder\mnt and notice a folder named xxxxxx, which contains a folder named after the project you were invited to.
3. Get removed from the project.
4. Run `dir` or `ls` in \coder\mnt again.
5. Notice folder named xxxxxx is still there but empty.

**Expected behavior**
When you are removed from all projects by a user, the folder in \coder\mnt is also removed so you don't have an empty folder.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [68.0.3440.75 (Official Build) (64-bit) (cohort: 68_75_win)]

**Additional context**
Running `rmdir` on the empty directory successfully removes the folder, but I would rather it be removed automatically so I don't think I have anything in that folder if it is empty, unless, of course, there is a specific reason for this behavior.

**Comment by sreya92** [comment]
This was a recent change in behavior but it is working as designed. The mount point is retained in order to enable mounting a project even if a user's container is completely full.

**Comment by pokemonlover1234** [comment]
Ok that answered my question. Thanks
