### ISSUE TITLE
QA: IDE: Editor lags when typing

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#82]
**Describe the bug**
When the user is typing in the editor, the text lags. After clicking the mouse several times, the text will then quicken and catch up to where the last character was typed. It's a sporadic problem that comes and goes over a period of hours. The connection is 300 down 50 up.

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'Open in IDE'
3. Open a new or pre-existing file
4. Start coding
5. Observe the behavior

**Expected behavior**
For the text to appear on screen as it's being typed with the keyboard.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Chrome
 - Version 68.0.3440.75 

**Additional context**
Location of this instance: Eastern US
Proxy/vpn: No

It's not something that I can reproduce at the moment, but it's something to keep an eye on.

**zendesk ticket**
338

**Comment by Xenofuscus** [comment]
I would add that it would a good idea to check htop/container resource usage if this happens again.
