### ISSUE TITLE
can't subscribe to updates on the status page 

### ISSUE THREAD

**Issue by Mczty** [codercom/bugs#83]
**Describe the bug**
the `subscribe to updates` button on the status page doesn't do anything.
**To Reproduce**
1. Go to https://status.coder.com
2. Click on 'subscribe to updates'
4. Observe

**Expected behavior**
it allows me to subscribe to updates.

**Screenshots**
I don't think screenshots are necessary but if you don't know what the button looks like, https://l.korzq.xyz/70b27a.png

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14 Beta (18A314h)
 - Browser: Google Chrome Canary
 - Browser Version: Version 70.0.3504.0 (Official Build) canary (64-bit)

**Additional context**
none

**Comment by NGTmeaty** [comment]
Can't reproduce, Windows 10, Google Chrome Stable.

**Comment by deansheather** [comment]
Can't reproduce this on Chromium on Linux:
![screenshot](https://owo.whats-th.is/648937.png)

Have you tried disabling your extensions? Are there any issues in the console when you click on the button?

The status page is powered by statuspage.io by Atlassian. If you can help us reliably reproduce this problem we can contact them about it on your behalf.

**Comment by Mczty** [comment]
I can also repro using chrome, chromium, safari on macOS Mojave

**Comment by kylecarbs** [comment]
Seems to be working for me. Could you provide a video of whats happening? @Mczty

**Comment by Mczty** [comment]
hmm.. it seems to be working now since I came back from China. I guess you can't assess it in mainland China. Sorry.
