### ISSUE TITLE
Backend: container stopped/moved hosts while being used

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#84]
**Describe the bug**
User was working in the IDE and the IDE stopped responding and external SSH client disconnected. When reconnecting to the IDE, they discovered that the container had changed public IP address (implying that the container had been stopped and moved to another host).

This could be because the container timed out and as a result the user was disconnected. In that case, there should be a feature request made about warning the user before the container is stopped.

**To Reproduce**
1. Open the IDE
2. Use it for a while (???) and connect to it externally via SSH
3. Notice that it freezes and external SSH connections break
4. Reconnect to the container in the IDE and notice that the SSH external IP has changed (signifying that it had been turned off and moved)

**Expected behavior**
The container should not stop while being used without a warning in advance.

**Screenshots**
n/a

**Additional context**
Reported via Discord.

**Comment by deansheather** [comment]
Possibly related to #102.

**Comment by kylecarbs** [comment]
This was due to lease expiring. Has been fixed.
