### ISSUE TITLE
Sign up issues still persistent for India based phone numbers

### ISSUE THREAD

**Issue by nol166** [codercom/bugs#85]
**Describe the bug**
A user has attempted to sign up for their coder.com account after the fix for India based phone numbers has been deployed suggesting that the issue may still not be addressed or there is another issue at play.

**To Reproduce**
1. Go to coder.com
2. Click on sign up
3. Enter in phone number with (+91)

**Expected behavior**
User receives a verification code.

**Comment by ThyLeader** [comment]
A fix was rolled out earlier that fixes this specific user's issue
