### ISSUE TITLE
UI freezes after submitting mobile verification code

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#88]
**Describe the bug**
A user went through the verification process to login. The UI froze after submitting the mobile verification code which they received on their phone. There's no way to continue or restart the process.

**Steps to Reproduce**
1. From the homepage, click ```Signup```
2. Go through the signup process
3. Submit your information
4. Get your verification code via text
5. Enter your verification code and submit
6. Notice the behavior

**Expected behavior**
User is directed to their new dashboard

**Mobile (please complete the following information):**
Waiting for user browser and mobile OS information
Testing various combinations in the meantime.

**zendesk ticket**
334

**Comment by kylecarbs** [comment]
Should be fixed.
