### ISSUE TITLE
Explorer: inconsistent explorer state to the actual disk

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#89]
**Describe the bug**
Explorer doesn't show files or folders that are on disk, or displays an outdated state.

**To Reproduce**
1. Open IDE
2. Open explorer
3. Open terminal
4. Run `npm install materialize-css`
5. Expand `node_modules/materialize-css/dist/css` folder in explorer
6. Notice that no files are listed in that folder
7. `ls node_modules/materialize-css/dist/css`
8. Notice that there actually are files in the folder

I've noticed this a few times myself, but have been unable to reliably reproduce it.

**Expected behavior**
The explorer should reflect the actual state of the disk.

**Screenshots**
User provided videos (demonstrate two different forms of inconsistencies with disk):
https://app.frame.io/r/a52fea2a-3f9b-4722-920e-4da49fe72b1f
https://app.frame.io/r/a93933d0-9eac-4c85-a37d-ecacb607afec

**Desktop:**
Browser: Google Chrome Version 68.0.3440.75 (Official Build) (64-bit)
OS: Kubuntu 18.04 Plasma

**Additional context**
Reported via Zendesk `Tickets #345, #346`.

**Comment by deansheather** [comment]
Possibly related to #76.

**Comment by jaymeramsay** [comment]
Not able to reproduce this issue at the moment. Two files show up in Explorer and in the terminal 
![screen shot 2018-08-06 at 10 51 44 am](https://user-images.githubusercontent.com/28520845/43727230-ff387018-9966-11e8-9158-ef23561afd00.png)
( ``ls node_modules/materialize-css/dist/css``)

**Comment by jaymeramsay** [comment]
This issue has been fixed.
