### ISSUE TITLE
UT: Escape key not working on vim

### ISSUE THREAD

**Issue by Xenofuscus** [codercom/bugs#91]
**Describe the bug**
When using vim in the terminal, the escape key does not function as it should. ctrl-c works, however.

**To Reproduce**
1. Open a terminal.
2. Type `vim`.
3. Press `i` on your keyboard.
4. Type stuff.
5. Try to press ESC to get out of it, but this does not work.

**Expected behavior**
Escape should lead me to exit editing mode in vim and allow me to exit vim successfully.

**Desktop (please complete the following information):**
 - OS: Linux 
- Browser: Chrome 67.0.3396.99

**Comment by ThyLeader** [comment]
Vimium is known to cause this

**Comment by ThyLeader** [comment]
@Xenofuscus can you confirm if you're using the vimium chrome extension?

**Comment by Xenofuscus** [comment]
No, I am not using the extension.

**Comment by nol166** [comment]
This issue has been resolved

**Comment by ammario** [comment]
If others have trouble with this, consider `Ctrl + [` instead. It is an ergonomic replacement for ESC in the terminal.
