### ISSUE TITLE
Deleted projects still appear in the file directory

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/bugs#93]
**Describe the bug**
After the user deletes a project from his dashboard, he can still see it listed in his file directory.

**To Reproduce**
1. Go to 'dashboard'
2. Either create a new project or select a pre-existing project
3. Click on the drop-down icon to the right
4. Click DELETE
5. Open the IDE in a different project
6. Find your file path in the upper left corner in the Explorer. example:
```HOME/coder/mnt/username/project```

7. Click on your username to show all of your available projects folders
8. Notice that the deleted project still appears

**Expected behavior**
The deleted file to not appear

**Zendesk ticket number**
367

**Comment by jaymeramsay** [comment]
This should be fixed.

**Comment by deansheather** [comment]
A user in Discord and Zendesk reported this issue again today.
