### ISSUE TITLE
Phone Verification: some users can't change country code

### ISSUE THREAD

**Issue by deansheather** [codercom/bugs#94]
**Describe the bug**
Some users are reporting that they can't change the country code while signing up.

**To Reproduce**
1. Go to signup page
2. Enter a valid alpha key and continue
3. Try to change the phone number country code
4. Notice that you can't change the country code

**Expected behavior**
Users should be able to change the country code.

**Workaround**
Paste the following in devtools console in your browser (change the `+1` to the desired country code):
```
document.getElementById('sub-phonenumber').value = '+1';
```

**Screenshots**
n/a

**Desktop:**
Windows 10  Pro version 1803 build 17134.165
Chrome version 68.0.3440.84

**Additional context**
Reported multiple times via Zendesk and Discord.

**Comment by jaymeramsay** [comment]
Hey Dean, this is a known issue that we're working on.  For now, the ```+1``` is hardcoded in the front end, but it shouldn't affect the users ability to log in. Is part of the problem that the inability to enter the country code is preventing users from logging in?

**Comment by deansheather** [comment]
Only affects users who are signing up. Doesn't affect people who have already registered and want to login.

**Comment by jaymeramsay** [comment]
This issue has been fixed. If any further instances occur, please let us know!
